### ISSUE TITLE
综合讨论

### ISSUE THREAD

**Issue by fangfeng-0214** [coding-newbies-group/programming-co_creation-docs#1]
表格不是 markdown 所擅長的事情，以后的学习过程中的表格若是复杂了，markdown可能就应付不了。就如同笑来老师讲markdown处理图片也是有欠缺的

**Comment by vwumumu** [comment]
> 表格不是 markdown 所擅長的事情，以后的学习过程中的表格若是复杂了，markdown可能就应付不了。就如同笑来老师讲markdown处理图片也是有欠缺的

这个问题是我需要收集大家的基本信息，想着能放到github中，因此建议了markdown，但确实有问题，自己也在平衡，没想到太好的办法
用google sheet可能更好，但是担心google sheet增加大家的前期麻烦，可能很多人没有用google，也不想用的工具太分散，尽量一站搞定。
暂时，先接龙记到trello里吧。

**Comment by vwumumu** [comment]
> 表格不是 markdown 所擅長的事情，以后的学习过程中的表格若是复杂了，markdown可能就应付不了。就如同笑来老师讲markdown处理图片也是有欠缺的

已经调整为腾讯文档了。
