### ISSUE TITLE
编程作业提交指南，小白的卡点，我得记录下

### ISSUE THREAD

**Issue by Zhangjuanlli** [coding-newbies-group/programming-co_creation-docs#105]
> 系统：Windows10
> 编译器：VSCode
> Python版本：3.11.2
> 我的报错（提供报错）：下载并安装PicGo，桌面出现的快捷图标，双击之后桌面上没有出现PicGo页面。
![image](https://user-images.githubusercontent.com/68979481/225160076-ae07c7cb-ee15-4b0b-96d5-fa071dbb5201.png)

事实是我的页面直接隐藏到任务栏。
![image](https://user-images.githubusercontent.com/68979481/225161139-f8fffdaa-dca9-4f94-8b47-21d24e65721f.png)

这个问题卡了我两天，事情发生和解决的具体过程如下：

先说说不到一个月时间，对共学共创营的感受。
Mumu老师为了共学共创营的伙伴们既能在学习过程中充分沟通交流，又能记录个人的问题，还能真正学到技能，用github上的issue,让大家记录自己学习的问题；建立mixin共学共创群，发出自己的问题，思想的火花，大家即时形成讨论的氛围，得到即时的反馈；还用心设计了这个编程作业提交指南，让大家把自己最后通过独立思考操作完成的作业经过技术组的同学的检验得到确认：这个技能确实掌握了。
在搭建提交作业环境的过程中，又是个人技能提升的打怪升级之旅。

> 1.创建Github的images仓库    
>     https://github.com/new
 没有卡点，一气呵成 

> 2.创建Github Token                      
> https://github.com/settings/tokens

>3.设置PicGo
>下载并安装PicGo，下载连接：

>[Windows](https://github.com/Molunerfinn/PicGo/releases/download/v2.3.1/PicGo-Setup-2.3.1-ia32.exe)

下载安装PicGo都是顺利的，可安装完成了，电脑桌面上也出现了PicGo的操作快捷按钮，我双击快捷图标，一个快闪之后，桌面上没有出现我期待的文档提示的页面。我安装的PicGo 怎么了，去哪了？我怀疑自己的安装过程有问题，于是卸载了前面安装的，重新下载安装，可结果一样，双击桌面快捷图标就是不见页面。
郁闷中的我截图发群求助，有同学提示我要“打开”，还是没能解决我的问题。
![image](https://user-images.githubusercontent.com/68979481/225158497-8f8c21b3-1b0e-4b89-8a7f-8bea5839f195.png)

之后，Mumu 看到我说这个问题卡了我两天，提出看看我的实际情况，用腾讯会议共享桌面的方式，Mumu 要我把光标移到任务栏的显示隐藏图标按钮。真相大白，我打开的PicGo,一打开就跑到任务栏隐藏起来了。而我全然不知，这个问题之前的同学都没碰到呢，还是他们双击快捷图标，页面显示在桌面？

**Comment by elastigirlYY** [comment]
> > 系统：Windows10
> > 编译器：VSCode
> > Python版本：3.11.2
> > 我的报错（提供报错）：下载并安装PicGo，桌面出现的快捷图标，双击之后桌面上没有出现PicGo页面。
> > ![image](https://user-images.githubusercontent.com/68979481/225160076-ae07c7cb-ee15-4b0b-96d5-fa071dbb5201.png)
> 
> 事实是我的页面直接隐藏到任务栏。 ![image](https://user-images.githubusercontent.com/68979481/225161139-f8fffdaa-dca9-4f94-8b47-21d24e65721f.png)
> 
> 这个问题卡了我两天，事情发生和解决的具体过程如下：
> 
> 先说说不到一个月时间，对共学共创营的感受。 Mumu老师为了共学共创营的伙伴们既能在学习过程中充分沟通交流，又能记录个人的问题，还能真正学到技能，用github上的issue,让大家记录自己学习的问题；建立mixin共学共创群，发出自己的问题，思想的火花，大家即时形成讨论的氛围，得到即时的反馈；还用心设计了这个编程作业提交指南，让大家把自己最后通过独立思考操作完成的作业经过技术组的同学的检验得到确认：这个技能确实掌握了。 在搭建提交作业环境的过程中，又是个人技能提升的打怪升级之旅。
> 
> > 1.创建Github的images仓库
> > https://github.com/new
> > 没有卡点，一气呵成
> 
> > 2.创建Github Token
> > https://github.com/settings/tokens
> 
> > 3.设置PicGo
> > 下载并安装PicGo，下载连接：
> 
> > [Windows](https://github.com/Molunerfinn/PicGo/releases/download/v2.3.1/PicGo-Setup-2.3.1-ia32.exe)
> 
> 下载安装PicGo都是顺利的，可安装完成了，电脑桌面上也出现了PicGo的操作快捷按钮，我双击快捷图标，一个快闪之后，桌面上没有出现我期待的文档提示的页面。我安装的PicGo 怎么了，去哪了？我怀疑自己的安装过程有问题，于是卸载了前面安装的，重新下载安装，可结果一样，双击桌面快捷图标就是不见页面。 郁闷中的我截图发群求助，有同学提示我要“打开”，还是没能解决我的问题。 ![image](https://user-images.githubusercontent.com/68979481/225158497-8f8c21b3-1b0e-4b89-8a7f-8bea5839f195.png)
> 
> 之后，Mumu 看到我说这个问题卡了我两天，提出看看我的实际情况，用腾讯会议共享桌面的方式，Mumu 要我把光标移到任务栏的显示隐藏图标按钮。真相大白，我打开的PicGo,一打开就跑到任务栏隐藏起来了。而我全然不知，这个问题之前的同学都没碰到呢，还是他们双击快捷图标，页面显示在桌面？

我是苹果系统，也是遇到同款问题，在百度上查了好久，最后还是在github一篇文章中看到这是因为改版后会自动跳到顶部的菜单栏，要自己手动点开。同喜我们现在都解决好这个问题了～小白之路还很漫长，加油吧！
