### ISSUE TITLE
0-1.前期准备:无法安装Mixin Messenger电脑版

### ISSUE THREAD

**Issue by gzypy** [coding-newbies-group/programming-co_creation-docs#106]
多次卡在准备篇的各种必要安装上，求教两个问题，一是必须安装哪几个软件，怎么判断我电脑是否安装好？二是我的笔记本电脑是惠普win10家庭版，安装教程链接还是装不上电脑版mixin（有梯子）。

**Comment by Zhangjuanlli** [comment]
你现在安装了哪个软件，按照课程的顺序一个一个做，具体哪个卡住了，截图到群里，有经验的同学会有人回复你。
电脑版的mixink卡在哪一步，还是要具体问题具体分析

**Comment by vwumumu** [comment]
1.课程中需要装的就是要用的，按照教程能向下走，能用就代表安装好了；
2.Windows Mixin, 下载这个安装：https://github.com/MixinNetwork/flutter-app/releases/download/v0.38.7/mixin_desktop_windows_setup_amd64.exe；

**Comment by gzypy** [comment]
> 你现在安装了哪个软件，按照课程的顺序一个一个做，具体哪个卡在哪里了，截图发出来，或者到群里，有经验的同学会有人回复你。 比如电脑版的mixin卡在哪一步，截图黏贴在这个ISSUE里，可以针对你的具体问题给出解决方法。

现在确认了一下，git,python37,powershell三项可以啦，mixin晚上群友发给我安装程序。有这四项够吗？另外怎么贴截图？（prt scr屏幕截图后怎么操作？）

**Comment by vwumumu** [comment]
你这个思路不对，不用统计现在装了哪些，按照课程顺序从头往下走，走到哪卡住解决哪的问题就可以了。
截图后Ctrl + V直接粘贴进Issues就可以了。

可以参考这个issues：https://github.com/coding-newbies-group/programming-co_creation-docs/issues/24

学了提交Issues，先搜一下看有没有问过同样的问题，如果没有，就开一个新问题。

**Comment by gzypy** [comment]
谢谢大家，问题已经解决，我关闭issue
