### ISSUE TITLE
7.逻辑判断与分支  替换了代码 但 试验时还是上节课的效果，感觉代码没起作用?如何暂停机器人?

### ISSUE THREAD

**Issue by skymapcn** [coding-newbies-group/programming-co_creation-docs#107]

**Comment by AndyZhou6688** [comment]
在命令行按Ctrl+C可以终止机器人运行

**Comment by Fangewa** [comment]
先在vscode保存Ctrl+S，然后再运行机器人试试

**Comment by Zhangjuanlli** [comment]
show me your code
或者截屏出来，只有标题，大家只能猜想你肯遇到什么卡点

**Comment by vwumumu** [comment]
把所有的命令行窗口都关掉，保存新代码，打开新的命令行运行新代码。

**Comment by skymapcn** [comment]
> 
const { BlazeClient } = require("mixin-node-sdk");
const client = new BlazeClient(
    {
        "pin": "612427",
        "client_id": "d9146ab0-375a-4f92-a607-3bfc05d83e0b",
        "session_id": "0bbe55b9-4533-40ef-a679-ae62c6f985b6",
        "pin_token": "NqNgKeq1AuB7TdPjSbOinAW3NtzBpLSrWq2_kx1jZEE",
        "private_key": "r8dYDaBl88CADeuNMshcf9o8eF_3ZMyUAAZMEEL8ttgOuqPHBiKXYNpyuXAdLDS_t3Bvf6ikSti8IKsBDHo1Lg"
      },
  // 上面{ }内的信息替换成您自己Mixin机器人的私钥信息
  { parse: true, syncAck: true }
);

client.loopBlaze({
  onMessage(msg) {
    console.log(msg);
    // if (msg.data === "你好") {
    //   client.sendMessageText(msg.user_id, "你也好！");
    // } else if (msg.data === "你是谁") {
    //   client.sendMessageText(msg.user_id, "我是编程学习小助手");
    // } else {
    //   client.sendMessageText(msg.user_id, "我不知道你在说什么");
    // }
    if (msg.data === "你好") {
      client.sendMessageText(msg.user_id, "你好！");
    }
    
    if (msg.data === "你好") {
      client.sendMessageText(msg.user_id, "你也好！");
    }
  },
  onAckReceipt() {},
});

**Comment by skymapcn** [comment]
> 

收到， 按照此步骤问题解决。  谢谢
