### ISSUE TITLE
扩展，编程作业提交指南

### ISSUE THREAD

**Issue by Zhangjuanlli** [coding-newbies-group/programming-co_creation-docs#108]
> 系统：Windows10
> 编译器：VSCode
> powershell
> typora
> Python版本：3.11.2
> 你的代码（描述操作）：print(Hello Python)
> 你的报错（提供报错）：
几天来，有几位刚刚起步的同学问学习环境营造过程中安装工具的困惑，而对于已经跟着营队走了20天的我来说，不同工具之间的切换的方法和意识需要加强。据我现在知道的知识点有：
> exit()是退出当前编辑路径的命令
> ctrl+c是node.js 中退出的命令
这两条具体在什么环境下用，还不清楚。
今天碰到的问题如图：
![image](https://user-images.githubusercontent.com/68979481/225500342-aa774c6b-ad23-4aca-95a5-af826abee78e.png)

在这里，我想找到之前python 中做的函数练习，怎么都出不来。

(https://user-images.githubusercontent.com/68979481/225500342-aa774c6b-ad23-4aca-95a5-af826abee78e.png)
这个上面截图的超级链接具体指的哪，既然是github用户有关，怎么把图片添加到前两天做的个人的images里。

**Comment by vwumumu** [comment]
没看懂你的问题是什么，麻烦再描述一下问题。

**Comment by AndyZhou6688** [comment]
问题1：在这里，我想找到之前python 中做的函数练习，怎么都出不来。
可能是你的函数练习所在的文件夹和截图中VSCode打开的文件夹不是同一个文件夹。检查练习使用的文件存在哪个文件夹，然后用VSCode打开这个文件夹就能看到。
问题2：这个上面截图的超级链接具体指的哪，既然是github用户有关，怎么把图片添加到前两天做的个人的images里。
使用git push把你保存图片的文件夹push到images仓库中，具体可参考：扩展资料-01.git的基本用法

**Comment by Zhangjuanlli** [comment]
今天再看自己昨天提的问题，就是傻问题，正如Mumu昨晚周会上所说，就不是问题，但也是那个当下的困境。

> exit()是退出当前编辑路径的命令
> ctrl+c是node.js 中退出的命令

上面第一句：exit()是python环境下退出当前编辑路径的命令
第二句：ctrl+c是node环境中终止当前运行的快捷命令

说到想找到之前python 中做的函数练习，实际就在截图中VScode左侧的标题栏，昨天不熟悉操作界面。

感谢大强对我的问题的理解和指点。感谢Mumu 的看见。
