### ISSUE TITLE
0-2.Markdown超简教程：无序列表和任务列表

### ISSUE THREAD

**Issue by freefunfee7** [coding-newbies-group/programming-co_creation-docs#11]
在进行超简教程学习时，不确定无序列表和任务列表怎样生成。
建议说明在Typora中如何生成无序列表和任务列表：
无序列表：
在Typora中
（1）输入-
（2）然后再加一个空格
会生成1个无序列表
任务列表：
在Typora中
（1）输入-
（2）然后加一个空格
（3）然后输入左中括号[
（4）然后加一个空格
（5）然后输入右中括号]
（6）最后再加一个空格
会生成1个任务列表

**Comment by vwumumu** [comment]
配套[视频](https://www.bilibili.com/video/BV1Ho4y1v79V/?vd_source=4a888db8814702b2062fcaf2575be745) 5：50 秒开始有讲和展示源码：

![image](https://user-images.githubusercontent.com/81784095/220603358-9e090908-4479-45cc-99c2-b3bfc3bea50a.png)

**Comment by freefunfee7** [comment]
好的，看了文档，视频还没看。
我也看看视频，谢谢大佬
