### ISSUE TITLE
插播1：编程作业提交指南   如何把 截图粘贴到 markdown 文件中，有时可以成功，有时失败。在issue 中没有问题。

### ISSUE THREAD

**Issue by skymapcn** [coding-newbies-group/programming-co_creation-docs#114]
这个截图如何粘贴到 markdown 文件中
![e7b2843e-241a-4ac0-ba71-881908fe8b83](https://user-images.githubusercontent.com/29712741/225665724-f981b3bd-40ab-4bac-a631-d427fc837f31.png)
![0ff5d732-28ef-428f-9f8a-7e076b3499d4](https://user-images.githubusercontent.com/29712741/225666246-c0a219a9-af27-49ee-a98c-dc475448bc47.png)

**Comment by AndyZhou6688** [comment]
使用编程作业提交指南中的方法截图时，1、需要保持“科学上网”状态，2、需要打开Picgo软件。必须同时满足以上两个条件。

**Comment by vwumumu** [comment]
从截图看，你Typora在源代码模式下，需要在非源代码的模式下粘贴截图。

**Comment by skymapcn** [comment]
> 解决了  太棒了 ，就是这个原因 。真是火眼晶晶 ，多谢 mumu 大佬
<img width="790" alt="image" src="https://user-images.githubusercontent.com/29712741/225954921-d5ef414f-c3c5-4e02-bfcc-55344402172e.png">

**Comment by Zhangjuanlli** [comment]
编程的活，容不得半点差错，经过编程的学习，我们锻炼成了只字不差阅读的能力，成就了火眼金睛的本事。
