### ISSUE TITLE
5.通过Github共创：本地修改完到powershell中git push 报错

### ISSUE THREAD

**Issue by 2020emmy** [coding-newbies-group/programming-co_creation-docs#115]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.10.3
> 你的代码（描述操作）：本地修改完到powershell中git push 报错
> 你的报错（提供报错）：
PS C:\Users\wam19\programming-co_creation-docs> git commit -m "modify assignment-submmit-guide.md"
[main 2cf7c97] modify assignment-submmit-guide.md
PS C:\Users\wam19\programming-co_creation-docs> git push
To github.com:2020emmy/programming-co_creation-docs.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'github.com:2020emmy/programming-co_creation-docs.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\wam19\programming-co_creation-docs>
![image](https://user-images.githubusercontent.com/75403976/225773001-599be9d0-91df-47ad-9c3c-e7549be44f09.png)

**Comment by vwumumu** [comment]
1. 在你的github仓库页面点击sync，将你的github仓库同步到最新内容；
2. 在命令行中，执行git pull，将最新的，你的github仓库拉取到本地；
3. 在命令行中，执行git push，将本地仓库，推送至你的github仓库；
4. PR

**Comment by vwumumu** [comment]
any feedback for this issues?

**Comment by 2020emmy** [comment]
谢谢mumu的解答，这个问题解决了已经
