### ISSUE TITLE
作业1-6：做个Mixin机器人，执行node index.js报错

### ISSUE THREAD

**Issue by cxiaoxiong** [coding-newbies-group/programming-co_creation-docs#120]
### 1.6机器人

> 系统：Windows10
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：创建Mixin机器人跟着教程走了两次，运行 node index.js 这一步，机器人创建成功，通过搜索可以找到机器人，但跑不起来，报错如下：
>
> ![](https://raw.githubusercontent.com/cxiaoxiong/images/master/%E6%9C%BA%E5%99%A8%E4%BA%BA.jpg)

![](https://raw.githubusercontent.com/cxiaoxiong/images/master/nodejs.png)

VScode的代码如下：

![](https://raw.githubusercontent.com/cxiaoxiong/images/master/%E6%9C%BA%E5%99%A8%E4%BA%BA.png)

我通过google ，查到可能是我前两年安装的node的版本（v13.0.1）过低造成的。于是就搜索如何更新node，使用下面的方法：

> ## 升级NodeJs方法一
>
> 方法一是很常规的做法，不借助第三方工具，window系统、苹果系统都适用。
>
> 就是去`Nodejs`官网下载最新版本，然后重新安装在原安装路径下（这样不用重新配环境变量），步骤如下：
>
> 1. 命令行里执行 `node -v`查看当前版本是否是最新版本
> 2. 查看之前的安装路径，使用命令 `where node`
> 3. 去[Nodejs官网](https://link.juejin.cn?target=https%3A%2F%2Fnodejs.org%2Fen%2Fdownload%2F)下载匹配你电脑操作系统的最新的mis长期稳定版LTS，按步骤安装，安装路径是上一步的路径
> 4. 最后测试是否安装成功，执行`node -v`打印出版本信息
>
> ## 升级NodeJs方法二
>
> 方法二是使用工具 `nvmw` 或者 `nvm`，window系统的使用 `nvmw`，苹果系统的使用 `nvm`(*实际测试发现windows系统也可以安装nvm)*，步骤如下：
>
> 1. 安装 `nvmw`
>
> ```
> npm install nvmw -g
> ```
>
> 1. 使用nvmw安装nodejs
>
> ```
> nvmw install v18.12.0
> ```
>
> 1. 使用nvmw临时使用某个版本的nodejs
>
> ```
> nvmw use v18.12.0
> ```
>
> 1. 使用nvmw切换本地的nodejs版本
>
> ```
> nvmw switch v18.12.0
> ```
>
> 1. 查看本地安装的所有nodejs版本
>
> ```
> nvmw ls
> ```
>
> 

更新node的方法，尝试过五六次，若干个方法，都没有成功，报错如下：

![](https://raw.githubusercontent.com/cxiaoxiong/images/master/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20230319215248.png)

暂时搞不定，希望技术组帮忙看看是不是node的版本问题，如果是，如何更好更新node？谢谢！

**Comment by cxiaoxiong** [comment]
已解决

**Comment by Fangewa** [comment]
好像是index.js建在node_modules文件夹里面了，试试建在multisig文件夹。

**Comment by cxiaoxiong** [comment]
> 好像是index.js建在node_modules文件夹里面了，试试建在multisig文件夹。

我检查了一下，没有建在node_modules文件夹里面了，是建在multisig文件夹哈

**Comment by cxiaoxiong** [comment]
![](https://raw.githubusercontent.com/cxiaoxiong/images/master/%E6%9C%BA%E5%99%A8%E4%BA%BA.png)

> 好像是index.js建在node_modules文件夹里面了，试试建在multisig文件夹。

**Comment by Zhangjuanlli** [comment]
你在Powershell里少了一步，看看这个截图，是否少了 :  code  .
![image](https://user-images.githubusercontent.com/68979481/226109299-32292c22-6a9a-431f-af9b-09eba916ed12.png)

**Comment by dgzbk790119** [comment]
建议重新对机器人私钥重新更新下，我曾经这个报错，重新更新了私钥后就解决问题。

**Comment by vwumumu** [comment]
在multisg目录，执行yarn，截图我看一下？

**Comment by cxiaoxiong** [comment]
在茂萍的帮助下，我用了下面方法更新成功，谢谢大家！

# windows10更新的node的方法

indows操作系统下，可使用工具 gnvm 管理NodeJs版本，步骤如下：

1. 首先安装gnvm

- 从Github下载安装 [32-bit](https://link.juejin.cn?target=https%3A%2F%2Fgithub.com%2FKenshin%2Fgnvm-bin%2Fblob%2Fmaster%2F32-bit%2Fgnvm.exe%3Fraw%3Dtrue) 或者 [64-bit](https://link.juejin.cn?target=https%3A%2F%2Fgithub.com%2FKenshin%2Fgnvm-bin%2Fblob%2Fmaster%2F64-bit%2Fgnvm.exe%3Fraw%3Dtrue)

1. 把下载的 gnvm.exe 文件放在NodeJs所在的安装目录，可通过 `where node` 查询；
2. 验证一下安装是否成功，执行 `gnvm version`
3. gnvm安装成功之后，用gnvm安装NodeJS的不同版本，gnvm会管理起来这些版本；

```js
gnvm install latest
gnvm install 18.12.0
gnvm update latest
复制代码
```

1. 查看安装了哪些NodeJs版本

```
gnvm ls
```

1. 切换不同的版本

```
gnvm use 18.12.0
```

1. 卸载不同的NodeJs版本

```
gnvm uninstall 18.12.0
```
