### ISSUE TITLE
0-4.使用命令行：命令行中用 code . 不能打开vs code

### ISSUE THREAD

**Issue by elastigirlYY** [coding-newbies-group/programming-co_creation-docs#125]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：macOS
> 编译器：VSCode
> Python版本：3.9.6
> 你的代码（描述操作）：
按照李骏老师的环境配置教程一步步操作，
<img width="1369" alt="截屏2023-03-18 12 31 03" src="https://user-images.githubusercontent.com/79432716/226103394-aed28108-8d29-494d-9af5-88925007a216.png">

之前都可以在命令行中通过 code .打开vs code，卸载一次vs code后就偶尔能打开。（卸载重装后，也重新安装了install ‘code’ commend in path）
<img width="574" alt="截屏2023-03-18 19 27 46" src="https://user-images.githubusercontent.com/79432716/226103276-048659e3-9b9b-424c-99dd-d1a5ca25ed3c.png">

<img width="1028" alt="截屏2023-03-18 19 37 36" src="https://user-images.githubusercontent.com/79432716/226103328-cbce73ac-afaf-40f0-8530-e62ccfae1842.png">

诡异的是，截图前的一次操作还打开了vs code，但是和以往打开的页面不一样，所以我怀疑我的电脑里是不是有两个版本的vs code

**Comment by vwumumu** [comment]
在terminal中执行whereis code，看看能找到几个code，把截图贴上来。

**Comment by LazzaroneS** [comment]
#### 提供一个检验 `install 'code' command in PATH` 这个操作成功没成功的方法。

![image](https://user-images.githubusercontent.com/41162617/226179050-254a4861-878f-4a6a-b653-5eff2ca73800.png)

如上图：
- 使用 `whereis code` 命令查看 VSCode 所在路径；
- 使用 `echo $PATH` 命令输出 PATH 变量；
- 如果 VSCode 所在路径去掉右边的 `/code` 剩余部分能够在 PATH 变量里面找到，就表示 `install 'code' command in PATH` 操作成功了。（冒号 `:` 是分隔符）

**Comment by cxiaoxiong** [comment]
如果命令行搞不定，下次想调用哪个文件夹，可以直接把想要使用的文件夹拖到 VScode的快捷键，就会自动打开，不用纠结一定要用命令哈。

**Comment by elastigirlYY** [comment]
截图没有显示地址和个数
<img width="570" alt="截屏2023-03-21 10 24 37" src="https://user-images.githubusercontent.com/79432716/226504780-fac0dca4-095f-4c78-b8db-a56344e6661a.png">

**Comment by vwumumu** [comment]
按图操作一下试试
![image](https://user-images.githubusercontent.com/81784095/226630059-8308f9db-fcf8-4ae6-8a1e-7170f2b74607.png)
