### ISSUE TITLE
5.通过Github共创—Github配置SSH登录，ssh密钥报错。

### ISSUE THREAD

**Issue by dgzbk790119** [coding-newbies-group/programming-co_creation-docs#127]
> 系统：Windows10
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：生成ssh key

在PowerShell中执行：

 ssh-keygen -t ed25519 -C "你的github邮箱地址"    该邮箱地址 已更换我自己邮箱地址了

> 你的报错（提供报错）：
![1679215940264](https://user-images.githubusercontent.com/120799913/226164154-806b6fe5-4124-4adb-a984-efadbd03e899.png)

**Comment by cxiaoxiong** [comment]
尝试这个命令看看： ` ssh-keygen -t rsa -C "username" `

**Comment by vwumumu** [comment]
怎么进入的powershell？powershell(x86)不支持该命令。参考下图，用红色框出来的powershell，不要用蓝色框出来的那些。
![image](https://user-images.githubusercontent.com/81784095/226173082-e511e9ce-1024-4a9f-860c-801c9d217650.png)

**Comment by vwumumu** [comment]
@dgzbk790119 看到issues关闭了，是什么问题造成的？

**Comment by dgzbk790119** [comment]
感谢木木老师的解答，已解决，谢谢
