### ISSUE TITLE
8.逻辑运算符  提议讲解一下代码规范，这样可以从一开始就养成 规范编写代码的习惯，另外也便于理解代码，避免错误。

### ISSUE THREAD

**Issue by skymapcn** [coding-newbies-group/programming-co_creation-docs#129]
8.逻辑运算符  提议讲解一下代码编写的规范，这样可以从一开始就养成 规范编写代码的习惯，另外也便于理解代码，避免错误。

比如缩进  ，比如括号 ，变量命名，
昨天在对比 代码时 括号的嵌套就看了半天，效率很差。

虽然是小白，还是希望按照专业的方式学习。：）

**Comment by LazzaroneS** [comment]
我也认为，只有用最地道的方式来学习，才有可能成为大师。我个人也一直在寻找最地道的方式来改变自己的学习；同时有些现实必须要面对：我们从前接受的教育很多就是不地道的，所以可能在学编程的时候，自己所采用的学习方式是不是地道的，可能自己也不是太确定。

这也正常。毕竟像 Mumu 和我这样的学生，也还只是处于中白的阶段，有诸多的短板和未知是自然的。或许我们可以一边学习，一遍寻找看看，有没有大师可以带带我们。

综上，我大体上认同上面战友的提议，我希望以尽可能专业的方式去学习，也会默认尽可能拿出我认为最专业的学习方式来与各位同学交流。不过，专业地道和快速上手能够应用有时候是需要权衡取舍的，偏好那个选项可能每个人也不太一样。

**Comment by RunJavaCode** [comment]
Python 代码规范可以参考 [PEP-8 Style Guide for Python Code](https://peps.python.org/pep-0008/)。

良好的代码会带来更好的可读性，看看下面的例子：
![Xnip2023-03-19_23-26-51](https://user-images.githubusercontent.com/43558972/226186526-745bb13e-156c-4100-bfac-af883352f9c9.png)
图一 未准守规范书写代码

![Xnip2023-03-19_23-26-57](https://user-images.githubusercontent.com/43558972/226186518-f44c9720-403b-4857-9f0d-f5b607dfdcf2.png)
图二 准守规范书写代码

**Comment by Zhangjuanlli** [comment]
最基础的内容是需要我们自己先去学习，自学是门手艺这本书有蛮多同学看了好几遍。比如缩进 ，比如括号 ，变量命名等，自己就可以明白了。
自己反复看了之后，依然不懂的问题提出来，大家一起讨论学习。这样的收获，是刻骨铭心的。

**Comment by vwumumu** [comment]
1.昨天在对比 代码时 括号的嵌套就看了半天，效率很差。//没明白具体是哪？可以详细说说吗？
2.我确实不太清楚专业的开发人员是按照什么规范去写代码的，我目前了解的情况是，首先有邹茂平同学提出的[PEP-8 Style Guide for Python Code](https://peps.python.org/pep-0008/)这样的某种语言的编码规范来说明，其次，关于变量命令，函数命名这个大家挺不一样的，比如我知道有的以下划线链接两个单词，比如get_name，有的以小驼峰作为命名规范，小驼峰就是第一个单词首字母小写，后面的单词首字母大写，比如getName。这跟团队习惯，特定编程语言偏好都有关系。
3.另外，除了命名规范，其他的规范，比如空格，空行，缩进，现在在VSCode中都是通过插件来实现的。
有各种语言的Beautify插件，然后在源代码页面，右键，有一个Format Document的选项，快捷键Shift Alt F，也就是说，实际操作中，根本不用考虑，写完后，一键就规范了。
![image](https://user-images.githubusercontent.com/81784095/226221636-d673e4c8-ebd8-40d3-8a59-dbb92765c611.png)
4.我不是专门做开发的，学习的过程中可能确实会有后面需要纠正的东西，其实我觉得这个过程也是每个人都需要经历的升级的过程，当然有适合大家遵守的总结好的规范，有依据的，欢迎PR

**Comment by skymapcn** [comment]
> Python 代码规范可以参考 [PEP-8 Style Guide for Python Code](https://peps.python.org/pep-0008/)。
> 
> 良好的代码会带来更好的可读性，看看下面的例子： ![Xnip2023-03-19_23-26-51](https://user-images.githubusercontent.com/43558972/226186526-745bb13e-156c-4100-bfac-af883352f9c9.png) 图一 未准守规范书写代码
> 
> ![Xnip2023-03-19_23-26-57](https://user-images.githubusercontent.com/43558972/226186518-f44c9720-403b-4857-9f0d-f5b607dfdcf2.png) 图二 准守规范书写代码

**Comment by skymapcn** [comment]
感谢各位大佬的解答以及资源分享。
