### ISSUE TITLE
8.逻辑运算符  下面这段没看明白    f'   是什么意思？

### ISSUE THREAD

**Issue by skymapcn** [coding-newbies-group/programming-co_creation-docs#131]
8.逻辑运算符  
 下面这段没看明白    f'   是什么意思？
<img width="558" alt="image" src="https://user-images.githubusercontent.com/29712741/226180576-6caba1e7-f758-46c8-99b9-a41dfd65b03b.png">

**Comment by skymapcn** [comment]
chatgpt:
The meaning of this code is to print the result of the Boolean expression "c > b and b > a", which is true if c is greater than b and b is greater than a, and false otherwise. The f-string syntax is used to insert the result of the expression into the printed message.

**Comment by vwumumu** [comment]
哦，应该提示一下，重点不在于哪些内容，主要是理解and，or，not连接的逻辑表达式的值是什么？and， or的规则是什么？f-string会放到字符与字符串的部分讲。
