### ISSUE TITLE
1-7.逻辑判断与分支：机器人响应不符合预期，回复错乱

### ISSUE THREAD

**Issue by freefunfee7** [coding-newbies-group/programming-co_creation-docs#132]
![image](https://user-images.githubusercontent.com/59427476/226292481-f2396557-03f7-4503-b51a-e5ae67f4a7d6.png)
问题情况如上图：当代码调整为教程里的代码时，我发送“你好”，机器人的回复会出现多条“我不知道你在说什么”

出现问题的经过如下：
1.在编写1-7教程里的代码时，想当然地自己写，编写了如下图的错误代码，执行node index.js
![image](https://user-images.githubusercontent.com/59427476/226293431-c7e9533c-8560-4295-9140-8d76694b5491.png)
2.发现通过和机器人对话不符合预期，发现上述代码里判断相等的符号，我写成了两个等号==，正确的应该要写三个等号===
3.我调整为3个等号===，重新执行node index.js
![image](https://user-images.githubusercontent.com/59427476/226293917-69e987be-63ff-4d37-920d-ff957753b405.png)
4.发现仍然和机器人的对话不符合预期
![image](https://user-images.githubusercontent.com/59427476/226294035-37cc50ea-7fc2-48fa-bd44-ff2867b018a2.png)
5.继续和教程里的代码做对比，发现我的代码里缺少了onAckReceipt() {}, 然后我把这段代码加上，如下图
![image](https://user-images.githubusercontent.com/59427476/226294253-cf545330-4cc2-4f85-845f-9df8fd2a4d5b.png)
6.现在我对比了自己的代码和教程的代码，确认是一致的，然后执行node index.js，但发现机器人的对话仍不符合预期，即我提出的issue问题：当代码调整为教程里的代码时，我发送“你好”，机器人的回复会出现多条“我不知道你在说什么”

我猜测问题出在了onAckReceipt() {}, 当我缺少onAckReceipt() {}, 已经出现机器人的回复会出现多条“我不知道你在说什么”。
然后当我补上onAckReceipt() {}, 再执行node index.js，机器人仍旧会循环回复多条“我不知道你在说什么”
现在不确定如何解决问题，大家有没有什么建议和指导，麻烦了

**Comment by RunJavaCode** [comment]
请问，你修改代码之后，有正确保存修改后的代码吗？

我觉得，问题的根源应该不是在 `onAckReceipt() {}`，因为不需要这个语句，也能实现消息回复的功能。

我下面的代码能正常运行，机器人正常回复消息：
<img width="790" alt="image" src="https://user-images.githubusercontent.com/43558972/226299297-bb9ba31d-c0ac-4dd6-956d-ef393bf5eeb8.png">

**Comment by freefunfee7** [comment]
> 请问，你修改代码之后，有正确保存修改后的代码吗？
> 
> 我觉得，问题的根源应该不是在 `onAckReceipt() {}`，因为不需要这个语句，也能实现消息回复的功能。
> 
> 我下面的代码能正常运行，机器人正常回复消息： <img alt="image" width="790" src="https://user-images.githubusercontent.com/43558972/226299297-bb9ba31d-c0ac-4dd6-956d-ef393bf5eeb8.png">

@RunJavaCode  嗯有保存修改后的代码，我的现象是机器人会回复，但是当我输入“你好”，它会回多条“我不知道你在说什么”。
所以我猜测会不会是onAckReceipt()导致的。

然后我再次看了下你这个截图，我发现我的代码里缺少了{ parse: true, syncAck: true } 我把这段代码加到BlazeClient的初始化后，机器人终于正常了
深深为自己没有完整看全代码而感到囧囧囧，感谢你的回复，现在机器人终于正常了谢谢。
具体{ parse: true, syncAck: true } 为什么会导致机器人消息的异常，我之后研究研究。

**Comment by freefunfee7** [comment]
@RunJavaCode 非常感谢，解决了我的疑惑，谢谢你深入的解答。也激励了我要更深入去探究学习，谢谢。

**Comment by Zhangjuanlli** [comment]
从彼此的问题中学到更多。我自己的机器人碰巧完成了，正常动起来了，但到底是如何动的，怎样就不会动了，还真不知道。从你们的互动中又看到多了一个面。
