### ISSUE TITLE
1-7.逻辑判断与分支：机器人响应不符合预期，有时回复一条有时回复2条

### ISSUE THREAD

**Issue by Joyics** [coding-newbies-group/programming-co_creation-docs#133]
<img width="586" alt="image" src="https://user-images.githubusercontent.com/83849603/226487403-7d99b237-1cb0-4095-ab37-ff4cefa58e5e.png">
<img width="737" alt="image" src="https://user-images.githubusercontent.com/83849603/226487110-1ad31dd9-5797-47a3-9701-1cbb80b9aa47.png">

>  系统：macOS Ventura 13.1 
>  编译器：VSCode
>  Python版本：3.10.9
>  你的代码（描述操作）：机器人响应不符合预期
>  你的报错（提供报错）：
>
 ```
    client.loopBlaze({
    onMessage(msg) {
    if (msg.data === 1){
        client.sendMessageText(msg.user_id, "good");
      } else if (msg.data === "Have a nice day!") {
        client.sendMessageText(msg.user_id, "Thanks, I hope you have a lovely day as well!");
      } 
      else {
        client.sendMessageText(msg.user_id, "No");
      }
    },
    onAckReceipt() {},
  });
 ```

**Comment by Dada01Github** [comment]
这种情况，一般是一个机器人（同一个ID），部署了两套程序代码在运行。

**Comment by Fangewa** [comment]
如果有2个.js文件（可能它们都在运行）：
    那么在powershell里先运行一个node XX.js，然后Ctrl+c结束；
    再运行另一个，再Ctrl+c结束。
最后运行那个你想运行的.js文件。

**Comment by RunJavaCode** [comment]
> <img alt="image" width="586" src="https://user-images.githubusercontent.com/83849603/226487403-7d99b237-1cb0-4095-ab37-ff4cefa58e5e.png">
> 
> <img alt="image" width="737" src="https://user-images.githubusercontent.com/83849603/226487110-1ad31dd9-5797-47a3-9701-1cbb80b9aa47.png">
> 
> > 系统：macOS Ventura 13.1
> > 编译器：VSCode
> > Python版本：3.10.9
> > 你的代码（描述操作）：机器人响应不符合预期
> > 你的报错（提供报错）：
> 
> ```
>    client.loopBlaze({
>    onMessage(msg) {
>    if (msg.data === 1){
>        client.sendMessageText(msg.user_id, "good");
>      } else if (msg.data === "Have a nice day!") {
>        client.sendMessageText(msg.user_id, "Thanks, I hope you have a lovely day as well!");
>      } 
>      else {
>        client.sendMessageText(msg.user_id, "No");
>      }
>    },
>    onAckReceipt() {},
>  });
> ```

你这里的问题应该是终端中有两套机器人的代码在运行，可能是你修改并保存代码后，又在新的终端 Terminal 上使用了 `node index.js` 命令开启了一个新的机器人程序。

你可以尝试：
1、如果你使用的是 VScode 中的 Terminal 运行的代码，尝试退出 VScode 应用。然后重新打开 VScode，再进入 Terminal 重启机器人程序代码。

2、 如果你使用的是 PowerShell 应用，那么可以尝试退出所有的 PowerShell 应用。然后重新打开 PowerShell 应用，运行机器人程序代码。

**Comment by Joyics** [comment]
> 

确实是这样，现在正常了，感谢

**Comment by MiliFeng** [comment]
#132 这两个issue 提问，我在进行机器人修改设置时候，也结合这两个问题中建议进行了操作，并没有解决问题。
