### ISSUE TITLE
0-5.通过Github共创

### ISSUE THREAD

**Issue by HOUDAOZHANG** [coding-newbies-group/programming-co_creation-docs#134]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows10
> Python版本：3.9.7
> 你的代码（描述操作）：ssh-keygen -t ed25519 -C "13615171272@139.com"
> 你的报错（提供报错）：ssh-keygen : 无法将“ssh-keygen”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ssh-keygen -t ed25519 -C "13615171272@139.com"
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ssh-keygen:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

![image](https://user-images.githubusercontent.com/64313199/226786023-e348dd1d-c2a7-4259-b952-5e3ffe42ecc2.png)

**Comment by Dada01Github** [comment]
我用你提供的指令ssh-keygen -t ed25519 -C "13615171272@139.com" 是可以运行的，如下图；建议检查一下你的 Powershell 环境，可以参考一下，p0-4-cli.md共创文档，重新下载安装该环境。
![image](https://user-images.githubusercontent.com/125847418/226792306-f99f7827-4b2f-460c-b264-3a8cbe295d1a.png)

**Comment by RunJavaCode** [comment]
应该是没有将 ssh-keygen 配置成全局变量，导致不能使用这个命令。

**Comment by vwumumu** [comment]
参考这个：https://github.com/coding-newbies-group/programming-co_creation-docs/issues/127

**Comment by HOUDAOZHANG** [comment]
用错程序Windows PowerShell (x86)，
谢谢mumuwu
现用Windows PowerShell 正常。

**Comment by vwumumu** [comment]
@HOUDAOZHANG 看到问题解决了，我把它关掉了，下次问题解决后可以关一下issue，谢谢。
