### ISSUE TITLE
插播1：多次下载后，运行时显示文件损坏

### ISSUE THREAD

**Issue by wangjinghao1123** [coding-newbies-group/programming-co_creation-docs#135]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：print(Hello Python)
> 你的报错（提供报错）：
>
> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```
<img width="250" alt="截屏2023-03-22 下午4 05 38" src="https://user-images.githubusercontent.com/83558176/226838566-aa88eb21-3f25-486d-a309-02a3dab957d3.png">

**Comment by Ayan0217** [comment]
是MAC系统不？
系统偏好设置->安全性与隐私->选择“任何来源”

![Xnip2023-03-22_18-19-15](https://user-images.githubusercontent.com/104815761/226873675-c0650a77-811d-4667-b75d-71014f65974e.jpg)

**Comment by Zhangjuanlli** [comment]
＠
＞　Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：print(Hello Python)
> 你的报错（提供报错）：

>　>>> print(Hello Python)
＞　 File "<stdin>", line 1
＞  print(Hello Python)
          ^^^^^^^^^^^^
＞　SyntaxError: invalid syntax. Perhaps you forgot a comma?

以上部分内容，留下与你的ｉｓｓｕｅ有关的部分，添加上需要他人回复的，删掉无关的部分奥

**Comment by Zhangjuanlli** [comment]
感觉这个issue 和 #123   的问题一样

**Comment by Joyics** [comment]
> ### 1. 允许“任何来源”开启
>开启“任何来源”的方法如下：
> 打开【启动台】，选择【终端】，输入：
> ```
> sudo spctl  --master-disable
> ```
> 然后回车，继续输入密码（密码输入时是不可见的），然后回车。
> 接着打开【系统偏好设置】，选择【安全性与隐私】，可以看到【任何来源】已经选定。
>  <img width="707" alt="image" src="https://user-images.githubusercontent.com/83849603/226960957-4f73458d-89b0-4bc8-91a8-a8d94c8bdbde.png">
> 接着打开文件进行安装。
> ### 2. 发现还是显示“已损坏，无法打开。 先不要将它移到废纸篓”，尝试用这种方法：
>  在终端粘贴复制输入命令（注意最后有一个空格）：
> ```
> sudo xattr -r -d com.apple.quarantine 
> ```
> ### 先不要按回车！先不要按回车！先不要按回车！先不要按回车
> 然后打开 “访达”（Finder）进入 “应用程序” 目录，找到该软件图标，将图标拖到刚才的终端窗口里面，会得到如下组合(如图所示)：
> ```
> sudo xattr -r -d com.apple.quarantine /Applications/PicGo.app
>```
> <img width="779" alt="image" src="https://user-images.githubusercontent.com/83849603/226964223-d01f5da2-4ccc-4cfa-a609-b7869b98b304.png">
> 接着重新打开安装软件，就可以正常安装了。
> 有可能安装还是提示损害，但实际已经安装完成。在 “应用程序” 目录找到该软件图标，打开它，在屏幕右上角找到小图标，点开即可
> <img width="796" alt="image" src="https://user-images.githubusercontent.com/83849603/226965741-85982919-22b8-4226-a534-dbe7d863541b.png">

**Comment by vwumumu** [comment]
长时间没有反馈，关闭了。
