### ISSUE TITLE
8.逻辑运算符  示例的代码是不是写错了 详见附图

### ISSUE THREAD

**Issue by skymapcn** [coding-newbies-group/programming-co_creation-docs#136]
8.逻辑运算符 示例的代码是不是写错了 详见附图  是不是应该为 假
<img width="760" alt="image" src="https://user-images.githubusercontent.com/29712741/226929625-2f376768-b2ed-4e03-9487-86fb501dfc2e.png">

**Comment by AndyZhou6688** [comment]
![image](https://user-images.githubusercontent.com/85618947/227079879-a22b1760-9251-4f10-a081-ebfd0e1055ba.png)
我也认可战友的判断，不知道咱俩的判断对不对……True and False = False

**Comment by cxiaoxiong** [comment]
哈，我也觉得错了。

**Comment by vwumumu** [comment]
讲对了，那个中文写错了，typo，谢谢指正。

**Comment by cxiaoxiong** [comment]
> 讲对了，那个中文写错了，typo，谢谢指正。

这个例子应该说明，如果and有一个为Flase，那么if就不成立，后面的print()就不会被执行。
