### ISSUE TITLE
1-8.逻辑运算符：&&, 且

### ISSUE THREAD

**Issue by huixin-hub** [coding-newbies-group/programming-co_creation-docs#140]
> 系统：Windows11
> 编译器：VSCode
>我的代码：
<img width="699" alt="image" src="https://user-images.githubusercontent.com/77789025/227271161-62057b06-948c-4ccf-b1aa-46c9f448d064.png">
<img width="503" alt="image" src="https://user-images.githubusercontent.com/77789025/227271335-0a5fe833-78e0-4fea-aa9d-68a8156816d6.png">
> 我的报错：
<img width="513" alt="image" src="https://user-images.githubusercontent.com/77789025/227272266-656b3c26-57bf-42c2-a090-e0e15fc76f88.png">
问题：在VScode里保存后，在powershell运行时，按Ctrl+c，没有终止获取userID那一步的运行，运行node .\js,没有执行and，还是重复出现获取userid那一步，感觉是最上面三四行的问题，删删减减修修改改也没弄成功，作业还没完成，求助

**Comment by Dada01Github** [comment]
我看了下贴图，程序本身没有问题，user_id 已经通过 client.User(“xxx”),取到了你的user_id,
![image](https://user-images.githubusercontent.com/125847418/227392989-0cbc559e-0c68-4fef-85c5-6589de8cf3ce.png)
并将该user_id 写在了 第16行代码；因为没有终端发送消息可以参考，无法判断执行情况；你可以试试将第16行中 “===” 换成 “！==”做前后对比，试试机器人给你的回复。

**Comment by Dada01Github** [comment]
由于你已经取到了user_id,建议你把第18行程序通过“\\ client.User(“xxx”),”把该行代码暂时屏蔽执行，以免影响对消息的读取。

**Comment by Dada01Github** [comment]
由于你已经取到了user_id,建议你把第18行程序通过“\\ client.User(“xxx”),”把该行代码暂时屏蔽执行，以免影响对消息的读取。
