### ISSUE TITLE
1-9.循环：powershell中执行node文件的不同

### ISSUE THREAD

**Issue by 2020emmy** [coding-newbies-group/programming-co_creation-docs#141]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.10.3
> 你的代码（描述操作）：
>我使用powershell按照之前运行机器人的方式，直接node 1-9.js，只有光标闪烁，并不能打印出结果“h”.
后来查看视频，发现是要node .\1-9.js，然后结果运行出来了。
> 你的报错（提供报错）：

想问：
为什么两次运行node的格式和方式不同，有什么区别或者使用限制场景吗？
> ```
str = "hello"
console.log(str[0])
> ```

![image](https://user-images.githubusercontent.com/75403976/227383343-c2fe8de6-91c8-46bb-aec3-d07365ceb902.png)

**Comment by Dada01Github** [comment]
第一个 node index.js 是在当前目录下运行的；第二个node  .\1-9.js ;".\"表示当前目录下，没有区别；但如果要执行的文件是在下一级指定目录，就可以方便使用，如"node .\src\1-9.js"

**Comment by RunJavaCode** [comment]
> 问题：为什么两次运行node的格式和方式不同，有什么区别或者使用限制场景吗？

区别：
- `node index.js`：这种方式没有指定程序文件所在的文件夹路径，默认执行在当前文件夹中找到的指定程序文件。
- `node .\1-9.js`：这种方式指定了程序文件所在的文件夹路径，会到指定的文件夹路径中执行找到的指定程序文件。
    > `.` 表示当前目录

如果没有找到指定的文件，会报错。 比如说下面的 `node 1-8.js`
<img width="845" alt="image" src="https://user-images.githubusercontent.com/43558972/227703905-bc4f3f74-fc14-4693-b42c-31235073ddf7.png">


使用场景：
- 如果程序文件在你所处的文件夹中，直接使用 node 加上你想要执行的程序文件名即可。
  - `PS C: \Users\wam19\multisig> node index.js`
- 如果程序文件不在你所处的文件夹中，你可以使用指定文件夹路径的方式去执行
  - `PS C: \Users> node .\wam19\multisig\index.js`

上面两种方式的效果是完全一样的。


------------------------------------------------ 分割线 ------------------------------------------------

来个设想例子：

> 假设有一栋10层高楼，你住在没有厨房的 10 楼，厨房在 1 楼。某一天，你想下楼做饭。

把上面例子中的：
- 10层楼：当作目录的层级，如：`C: \Users\wam19\multisig`
- 下楼：当作 `cd` 命令
- 厨房：里面摆放的各种食材，当作一个一个程序文件， 如 `index.js`、`1-9.js`
- 做饭：当作使用 `node` 命令执行 程序文件

场景：
- 当你在10楼时，想做饭时，你必须先下到 1 楼，才能做饭。两个动作：
    - 下楼：`cd C: \Users\wam19\multisig`
    - 做饭：`node index.js` 或 `node 1-9.js`（等价于 node `.\1-9.js`）

- 当你在1楼时，不需要一层一层下楼，可以直接做饭吃。一个动作：
    - 做饭：`node index.js` 或 `node 1-9.js`（等价于 node `.\1-9.js`）

**Comment by vwumumu** [comment]
.\1-9.js是我输入1-9之后，按tab键“自动补全”出来的。也就是说，命令行当前路径有此文件。

**Comment by 2020emmy** [comment]
> .\1-9.js是我输入1-9之后，按tab键“自动补全”出来的。也就是说，命令行当前路径有此文件。

哈哈，明白了已经
