### ISSUE TITLE
0-5.通过 Github 共创-本地修改文档中，只需pr部分，不是全部修改都要提交pr时怎么操作

### ISSUE THREAD

**Issue by 2020emmy** [coding-newbies-group/programming-co_creation-docs#146]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.10.3
> 你的代码（描述操作）：github push时，提交 pull requset,出现了4个需要提交的文件，可其中一些做过修改的文档不需要提交，只需PR其中一个文件，这个怎么操作。
> 你的报错（提供报错）：
>
![image](https://user-images.githubusercontent.com/75403976/227660001-d0fb25e3-4bc0-499f-8b9e-689a60c0f14d.png)

> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```

**Comment by vwumumu** [comment]
同步你的个人仓库，然后提交PR，看看是否可以，还有一个笨办法，把你要提交的文件复制出来，然后把本地文件夹和github仓库删掉，重新fork，clone，然后把文件粘过去，进行git push，提交PR
![image](https://user-images.githubusercontent.com/81784095/227690386-7cadf409-1ba0-4081-9f6e-92e8fb52a6b9.png)

**Comment by LazzaroneS** [comment]
@vwumumu 她意思好像是有多个 commit, 然后提交 PR 时只想要某个 commit 被 pull.

---

@2020emmy 或许思路可以帮您捋一捋。

### 我对你截图的解读

你的仓库现在是 3 月 17 日有两个提交（commit），3 月 25 日有两个提交，一个在 7 分钟前，一个在 9 分钟前。如果我没有理解错的话，你应该是只想要 9 分钟前那个提交被 pull.

### 逻辑梳理

#### 关于 3 月 17 日的两次提交

3 月 17 日之后，由 Mumu 管理的主仓库有了不少更新了。如果你能在对自己电脑磁盘上的仓库做修改之前，先同步主仓库到你 Github 分叉出来的仓库，然后拉回自己的电脑磁盘。那么你就是在最新同步的主仓库内容上面做修改，那么你 3 月 17 日的两次提交就无关紧要了。

#### 关于 3 月 25 日的两次提交

如果你想要的只是 9 分钟之前的提交（commit），但是之后（7 分钟前）还有一次提交，那么可以回滚到 9 分钟之前的提交，再 pull 到自己的 Github 仓库，再提交 PR 是不是就可以了？

#### 操作步骤：

1. 先同步主仓库到自己 fork 的 Github 仓库，然后 `git pull` 到本地磁盘；
2. 然后做自己的修改和提交，使用命令 `git log` 查看最近几次提交：
![image](https://user-images.githubusercontent.com/41162617/227721019-ceda2e10-1670-47e4-8405-369ba92a03e0.png)
3. 敲 `git checkout 3f99e1` 回到 "commit 3f99e15bb203e869819a42c957e41ff10e532c34".
4. 敲 `git push origin HEAD:main` 把修改推到自己 fork 的 Github 仓库；
![image](https://user-images.githubusercontent.com/41162617/227721282-40b6a2c1-99cc-4f48-919a-4e14204d3a5c.png)
5. 回到 Github 提交 PR.
![image](https://user-images.githubusercontent.com/41162617/227721486-2726f76b-982e-4918-80ae-f2bc8318922e.png)

**Comment by 2020emmy** [comment]
> @vwumumu 她意思好像是有多个 commit, 然后提交 PR 时只想要某个 commit 被 pull.
> 
> @2020emmy 或许思路可以帮您捋一捋。
> 
> ### 我对你截图的解读
> 你的仓库现在是 3 月 17 日有两个提交（commit），3 月 25 日有两个提交，一个在 7 分钟前，一个在 9 分钟前。如果我没有理解错的话，你应该是只想要 9 分钟前那个提交被 pull.
> 
> ### 逻辑梳理
> #### 关于 3 月 17 日的两次提交
> 3 月 17 日之后，由 Mumu 管理的主仓库有了不少更新了。如果你能在对自己电脑磁盘上的仓库做修改之前，先同步主仓库到你 Github 分叉出来的仓库，然后拉回自己的电脑磁盘。那么你就是在最新同步的主仓库内容上面做修改，那么你 3 月 17 日的两次提交就无关紧要了。
> 
> #### 关于 3 月 25 日的两次提交
> 如果你想要的只是 9 分钟之前的提交（commit），但是之后（7 分钟前）还有一次提交，那么可以回滚到 9 分钟之前的提交，再 pull 到自己的 Github 仓库，再提交 PR 是不是就可以了？
> 
> #### 操作步骤：
> 1. 先同步主仓库到自己 fork 的 Github 仓库，然后 `git pull` 到本地磁盘；
> 2. 然后做自己的修改和提交，使用命令 `git log` 查看最近几次提交：
>    ![image](https://user-images.githubusercontent.com/41162617/227721019-ceda2e10-1670-47e4-8405-369ba92a03e0.png)
> 3. 敲 `git checkout 3f99e1` 回到 "commit [3f99e15](https://github.com/coding-newbies-group/programming-co_creation-docs/commit/3f99e15bb203e869819a42c957e41ff10e532c34)".
> 4. 敲 `git push origin HEAD:main` 把修改推到自己 fork 的 Github 仓库；
>    ![image](https://user-images.githubusercontent.com/41162617/227721282-40b6a2c1-99cc-4f48-919a-4e14204d3a5c.png)
> 5. 回到 Github 提交 PR.
>    ![image](https://user-images.githubusercontent.com/41162617/227721486-2726f76b-982e-4918-80ae-f2bc8318922e.png)

好的，谢谢@Atank的解答

**Comment by 2020emmy** [comment]
阿坦的理解非常正确，是我想要解决的问题，谢谢
