### ISSUE TITLE
如何将终端运行的python3 改为py？

### ISSUE THREAD

**Issue by Joyics** [coding-newbies-group/programming-co_creation-docs#148]
> 系统：macOS Ventura 13.1 
> 编译器：VSCode
> Python版本：3.10.9
> 如何将终端运行的python3 改为py？
>
> ![image-20230326115542213](https://raw.githubusercontent.com/Joyics/images/master/image-20230326115542213.png)

**Comment by pyz610173878** [comment]
![image](https://user-images.githubusercontent.com/31824264/227757797-3c0689e6-a25b-458c-8337-0a5d03fc29b7.png)

**Comment by dgzbk790119** [comment]
python3 改为py，需要进行以下操作：

1. 在终端输入以下命令，打开bash_profile文件：

vi ~/.bash_profile

2. 在bash_profile文件中添加以下内容：

alias py='python3'

3. 保存并退出bash_profile文件。

4. 在终端输入以下命令，使修改生效：

source ~/.bash_profile

现在，你可以在终端中通过输入py来运行Python 3了。例如，输入py test.py就可以运行test.py文件。

**Comment by Joyics** [comment]
感谢各位战友的启发，通过下面的设置解决了问题：

可以通过设置一个别名来将终端运行的“python3”改为“py”。要设置这个别名，请执行以下命令：

1.打开命令行终端

2.输入以下命令：

```bash
echo "alias py='python3'" >> ~/.bashrc
```

3.使别名生效：

```bash
source ~/.bashrc
```

现在，你可以在终端中使用“py”来代替“python3”了。例如，要运行Python脚本，只需键入“py”和脚本的路径即可。
