### ISSUE TITLE
8. 逻辑运算符 ：循环不起作用，不知那个环节有问题，麻烦大佬点评下。

### ISSUE THREAD

**Issue by dgzbk790119** [coding-newbies-group/programming-co_creation-docs#149]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：机器人
> 你的报错（提供报错）：
我按逻辑运算输入如下代码时：
![ee5c16a2-2cfc-4a44-ad56-27ecccd29dd1](https://user-images.githubusercontent.com/120799913/227760520-8340cc2e-859b-40d1-a03e-46cba1fda6a8.png)
机器人只会回复每天读书吧，不会回答其他答案，是否我设置有问题呢，麻烦大佬点下，谢谢。
![f25d9817-53a8-4e1f-a9b0-3d061edc77a2](https://user-images.githubusercontent.com/120799913/227760571-61c71caf-04ef-4abf-af7d-288c4c804318.png)

**Comment by freefunfee7** [comment]
@dgzbk790119 这一行代码
<img width="600" alt="image" src="https://user-images.githubusercontent.com/59427476/227772827-2662e592-73fa-4233-b48f-25fcfa1a78ea.png">
（1）“机器人只会回复每天读书吧”的原因是：
首先看!右侧的括号里的逻辑表达式，当msg.data和读书不等，并且msg.user_id和你的user_id相等时，结果是False&&True即False。然后!是取反，所以if里的整个逻辑表达式结果是False取反，那就是True。所以所以当你用你的用户向机器人发送文字（不是读书）时，都会进入这第一个if的语句块里，机器人此时会回复“每天读书吧！”

（2）根据这段代码的逻辑，当你用你的用户向机器人发送读书时，不会进入这第一个if的语句块里，机器人此时会回复“定投Box吧！”。这个原因是：
首先看!右侧的括号里的逻辑表达式，当msg.data和读书相等，并且msg.user_id和你的user_id相等时，结果是True&&True即True
然后!是取反，所以if里的整个逻辑表达式结果是True取反，那就是False。所以当你用你的用户向机器人发送读书时，不会进入这第一个if的语句块里，而是进入到
<img width="631" alt="image" src="https://user-images.githubusercontent.com/59427476/227773277-fa6a3607-9dd3-4884-9950-2c76b154e233.png">
这个if里的逻辑表达式此时结果为True，机器人会回复“定投Box吧！”

你可以多尝试修改取反!、与&&、或||的使用，观察下不同情况下，只要if里的逻辑表达式为True就会进入这个if里的语句块

**Comment by Dada01Github** [comment]
代码第16行，if（！（…））是这个“！”非 运算符在起作用，试试删除后，前后对比。

**Comment by LazzaroneS** [comment]
@freefunfee7 仿佛看到了大佬的大脑在不停运转和迭代，这对同行者是一种激励。😁

下面这段可以再思考思考：
> ……当msg.data和读书相等，并且msg.user_id和你的user_id相等时，结果是True&&True即True
然后!是取反，所以if里的整个逻辑表达式结果是True取反，那就是False。所以当你用你的用户向机器人发送读书时，不会进入这第一个if的语句块里，而是进入到
![image](https://user-images.githubusercontent.com/41162617/227774325-4bbda866-86d7-43b0-bc49-7f56d6dca11d.png)
这个if里的逻辑表达式此时结果为True，机器人会回复“定投Box吧！”

**Comment by LazzaroneS** [comment]
`if (!(msg.data === "读书" && msg.user_id === "9ea565...")) client.sendMessageText(msg.user_id, "每天读书吧！")`

这个 `if` 语句解析一下：
- 首先假定 `9ea565...` 这个 `user_id` 是钟康的（我查了一下并不是）；
- 然后这句话的意思就是：只要是钟康在给机器人发“读书”两个字，机器人就**不会**回复钟康“每天读书吧！”；同时除此之外，不管任何人给机器人发送任何消息，机器人都会回复发消息的人“每天读书吧！”

**Comment by dgzbk790119** [comment]
@LazzaroneS   这个ID是我的哈，所以没整明白。请你是那查到不是？麻烦指出，谢谢

**Comment by LazzaroneS** [comment]
![image](https://user-images.githubusercontent.com/41162617/227781469-45453c9d-4e20-40e6-ab25-77f8b444694b.png)

**Comment by Zhangjuanlli** [comment]
钟康没有解决的问题可以保持open，大家可以从你的问题和comment中获得启发奥
