### ISSUE TITLE
1-10：如何定义和初始化client变量

### ISSUE THREAD

**Issue by DSH5200** [coding-newbies-group/programming-co_creation-docs#153]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：print(Hello Python)
> 你的报错（提供报错）：
Node.js v18.14.2
PS C:\Users\W\multisig> node .\1-101.js
C:\Users\W\multisig\1-101.js:1
client.loopBlaze({
^

ReferenceError: client is not defined
    at Object.<anonymous> [90m(C:\Users\W\multisig\[39m1-101.js:1:1[90m)[39m
[90m    at Module._compile (node:internal/modules/cjs/loader:1254:14)[39m
[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:1117:32)[39m
[90m    at Module._load (node:internal/modules/cjs/loader:958:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)[39m
[90m    at node:internal/main/run_main_module:23:47[39m

在做1-10作业的过程中，借助chatGPT使用JavaScript中的字符串方法toLowerCase()将用户输入的字符串转换为小写字母，然后再与"hello"进行比较。

1. 在VSCODE里面输入以下代码
![image](https://user-images.githubusercontent.com/125792779/229263556-cf1ae8d7-d5c6-4cb1-bbd2-d0f012c39f94.png)

2. 在POWERSHELL里面运行 node .\1-101.js 出现结果如下
![image](https://user-images.githubusercontent.com/125792779/229263655-de2a19d3-bd4f-4bf1-bd1f-ac8f65254481.png)

chatGPT的回复也是很模糊
![image](https://user-images.githubusercontent.com/125792779/229263676-c7f40d9e-ba57-4b15-92ca-f5552f2246b9.png)

有同样遇到这种问题的伙伴，请指导下。多谢

**Comment by Dada01Github** [comment]
建议你参考作业1-6，将机器人client客户端相关的代码补完整。

**Comment by cxiaoxiong** [comment]
这段代码复制到 ``` index.js ``` 那个文件相应位置试一试，单独这段代码应该运行不起来。

**Comment by DSH5200** [comment]
> 这段代码复制到 `index.js` 那个文件相应位置试一试，单独这段代码应该运行不起来。

试了下，并没有出现我想要的结果
![image](https://user-images.githubusercontent.com/125792779/229271293-f7d59575-4eaa-4013-9e90-9fb058c1b876.png)

就是我想在powershell里面运行 node .\index.js后
可以输Hello, hello, HELLO 甚至 heLLo验证下

**Comment by LazzaroneS** [comment]
#### 原因分析
`ReferenceError: client is not defined`，从这个错误提示来看，你应该是还没有创建 Client 实例。好比打算开车，但是还没有车。

#### 解决方案
在使用上面的代码之前，先准备好你的创建 Mixin 机器人时的 keystore, 引入类 BlazeClient, 然后先创建 Client 实例。

可以参考我的 Client 实例创建代码：
```javascript
// 引入 Mixin 机器人的密钥信息，拥有这些信息就拥有了机器人的控制权。
// 如果不慎外泄，在 Mixin 开发者后台重新生成一次即可，旧的会被覆盖
import CLIENT_CONFIG from './config.json' assert { type: "json" }

// 引入 BlazeClient
import { BlazeClient, readNetworkAsset } from "mixin-node-sdk"
// 创建 BlazeClient 实例
let client = new BlazeClient(CLIENT_CONFIG, { parse: true, syncAck: true });
```

**Comment by DSH5200** [comment]
> #### 原因分析
> `ReferenceError: client is not defined`，从这个错误提示来看，你应该是还没有创建 Client 实例。好比打算开车，但是还没有车。
> 
> #### 解决方案
> 在使用上面的代码之前，先准备好你的创建 Mixin 机器人时的 keystore, 引入类 BlazeClient, 然后先创建 Client 实例。
> 
> 可以参考我的 Client 实例创建代码：
> 
> ```js
> // 引入 Mixin 机器人的密钥信息，拥有这些信息就拥有了机器人的控制权。
> // 如果不慎外泄，在 Mixin 开发者后台重新生成一次即可，旧的会被覆盖
> import CLIENT_CONFIG from './config.json' assert { type: "json" }
> 
> // 引入 BlazeClient
> import { BlazeClient, readNetworkAsset } from "mixin-node-sdk"
> // 创建 BlazeClient 实例
> let client = new BlazeClient(CLIENT_CONFIG, { parse: true, syncAck: true });
> ```

搞定了，谢谢大佬
