### ISSUE TITLE
为Github配置SSH登录，不清楚打开的PowerShell是哪个

### ISSUE THREAD

**Issue by fangfeng-0214** [coding-newbies-group/programming-co_creation-docs#17]
# 0-3 从我的截图上看，我的电脑是否装了太多的PowerShell, 是否需要卸载
> 系统：Windows10
> 编译器：powershell

我的应用里，P字母下有一个，W字母下Windows的有4个，我理解的区别是两个是管理员的权限，不知道我的这个情况是什么状况

![image](https://user-images.githubusercontent.com/68979481/220636139-c5463656-b1d3-48fc-b431-16e781079d49.png)

![image](https://user-images.githubusercontent.com/68979481/220944934-38ec58a2-3ddd-49dd-829f-522c1502be1d.png)

**Comment by vwumumu** [comment]
打开这个就可以：
![image](https://user-images.githubusercontent.com/81784095/220971675-6bbb5c09-f94e-41ae-83bc-5bf057a1b745.png)

**Comment by vwumumu** [comment]
@fangfeng-0214 这个问题有解决吗？如果解决了，请关闭一下这个Issues

**Comment by fangfeng-0214** [comment]
后缀带86的powershell版本过低，不适用。
