### ISSUE TITLE
项目篇：2-1.英语学习助手：

### ISSUE THREAD

**Issue by huixin-hub** [coding-newbies-group/programming-co_creation-docs#172]
> 系统：Windows11
> 编译器：VSCode
> <img width="935" alt="image" src="https://user-images.githubusercontent.com/77789025/232235559-73b8c905-db4f-4a75-9e35-ffde87524742.png">
> <img width="566" alt="image" src="https://user-images.githubusercontent.com/77789025/232235594-5618fa60-f93f-4f8a-ba6f-6ebce065fafb.png">
机器人回复的内容不是代码里const限制的固定值，代码看了好几遍，试了几次还是不行，求助

**Comment by dgzbk790119** [comment]
我也同样问题，期待老师给予答复，谢谢

**Comment by holtxu** [comment]
![image](https://user-images.githubusercontent.com/125620704/232255107-f0d45404-ae65-4ac8-8cc1-e14d10f06f2f.png)

注意用法
 1:定义需要拼接进去的字符串变量，可以拼接双引号与单引号
 2:将字符串变量用${}包起来，再写到需要拼接的地方,需要使用反向单引号: `  (键盘 Esc 下面那个键),而不是单引号: ' 

这个地方修改试试看。

**Comment by huixin-hub** [comment]
> ![image](https://user-images.githubusercontent.com/125620704/232255107-f0d45404-ae65-4ac8-8cc1-e14d10f06f2f.png)
> 
> 注意用法 1:定义需要拼接进去的字符串变量，可以拼接双引号与单引号 2:将字符串变量用${}包起来，再写到需要拼接的地方,需要使用反向单引号: ` (键盘 Esc 下面那个键),而不是单引号: '
> 
> 这个地方修改试试看。

**Comment by huixin-hub** [comment]
> 我也同样问题，期待老师给予答复，谢谢

我按照大佬给的建议，改为反向单引号就可以了，你也试试

**Comment by dgzbk790119** [comment]
我依照大佬意见作了修改，也可以了，谢谢。

**Comment by Zhangjuanlli** [comment]
我用的是反向单引号: ` (键盘 Esc 下面那个键),结果还是不对，而且我的消息滞后，通常我得再发一条消息，前面的一条回复才会出现：
![image](https://user-images.githubusercontent.com/68979481/232491554-26a90556-c77f-4d7a-9f15-5c7a4a210a9c.png)
![image](https://user-images.githubusercontent.com/68979481/232491649-f27438b1-91aa-487f-9eee-54586dd2a960.png)
![image](https://user-images.githubusercontent.com/68979481/232492000-9b3c3b5c-e0a7-452a-bb38-b1a4f9a81b7a.png)
