### ISSUE TITLE
2-1英语小助手：在代码的左边出现一条竖的波浪线，不知道是什么问题？另外，我的 ${text}提示“text未被定义，不明白。请大佬指点！

### ISSUE THREAD

**Issue by holtxu** [coding-newbies-group/programming-co_creation-docs#174]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

在代码的左边出现一条竖的波浪线，不知道是什么问题？另外，我的 ${text}提示“text未被定义，不明白。请大佬指点！

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：

![image](https://user-images.githubusercontent.com/125620704/232711006-cd7e1ff4-e047-48f1-9d4b-ffb98c1607d4.png)

> 你的报错（提供报错）：

![image](https://user-images.githubusercontent.com/125620704/232711148-a8b103fb-56c7-48f7-810b-b756e83e25de.png)

>
> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```

**Comment by Dada01Github** [comment]
![image](https://user-images.githubusercontent.com/125847418/232767376-55217f47-5b35-4640-9716-c38f8ba20279.png)
函数参数名称和函数内引用的不一致；或函数内未被声明定义，也会出现同样的问题。

**Comment by holtxu** [comment]
非常感谢志全大佬的解惑，可以了。

**Comment by Zhangjuanlli** [comment]
徐潮战友后来怎么修改的，图片贴出来让大家看到就好了

**Comment by holtxu** [comment]
![image](https://user-images.githubusercontent.com/125620704/233224375-7a9c7af8-aea8-4276-bc6b-5a6c70ec2161.png)
定义了就没有提示了，左边的那条波浪线还没有找到原因，好像也不影响运行。娟丽姐的学习精神值得学习！
