### ISSUE TITLE
2.1英语小助手：Cannot find module 'mixin-node-sdk/dist/client/conversation'

### ISSUE THREAD

**Issue by AndyZhou6688** [coding-newbies-group/programming-co_creation-docs#175]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：PS C:\Users\Andy\test> node index.js
node:internal/modules/cjs/loader:930
  throw err;
  ^
Error: Cannot find module 'mixin-node-sdk/dist/client/conversation'
Require stack:
> 你的报错（提供报错）： Cannot find module 'mixin-node-sdk/dist/client/conversation'
>
![image](https://user-images.githubusercontent.com/85618947/233024874-2ab7a99a-1a64-4ee5-ba73-ffe46c3e612a.png)
// Mix Bot
const { BlazeClient } = require('mixin-node-sdk');
const config = require("./config");
const client = new BlazeClient(
  {
    pin: config.pin,
    client_id: config.client_id,
    session_id: config.session_id,
    pin_token: config.pin_token,
    private_key: config.private_key
  },
  { parse: true, syncAck: true }
);

// ChatGPT
const { Configuration, OpenAIApi } = require("openai");
const { ConversationClient } = require('mixin-node-sdk/dist/client/conversation');
const configuration = new Configuration({
  apiKey: config.openai_key,
});
const openai = new OpenAIApi(configuration);

// WebSocket
client.loopBlaze({
  async onMessage(msg) {
    console.log(msg);
    if (msg.category === "PLAIN_TEXT") {
      const rawData = msg.data.toString();

      const lang = checkLanguage(rawData)

      rawZhData = "";
      rawEnData = "";

      if (lang === "Chinese") {
        console.log("Chinese");
        rawZhData = rawData;//中文
        rawEnData = await translate(lang, rawData);//英文
      } else if (lang === "English") {
        console.log("English");
        rawEnData = rawData;//英文
        rawZhData = await translate(lang, rawData);//中文
      } else if (lang === "Unknown") {
        console.log("Unknown");
        client.sendMessageText(
          msg.user_id,
          'Only English and Chinese are supported.\n仅支持英文或中文。'
        );
      }
      // 处理收到的消息

      //处理返回的消息
      const returnEnData = await conversation(rawEnData);//英文
      const returnZhData = await translate("English",returnEnData);//中文

      const res = `> 用户\n英文：${rawEnData}\n中文：${rawZhData}\n\n< 助手：\n英文：${returnEnData}\n中文：${returnZhData}`;

      client.sendMessageText(msg.user_id, res);
    } else {
      client.sendMessageText(msg.user_id, "Plain text only.\n仅支持文本。")
    }
  },
  onAckReceipt() { },
});

// Functions
function checkLanguage(text) {
  const firstCharCode = text.charCodeAt(0);
  if (firstCharCode >= 0x0000 && firstCharCode <= 0x007F) {
    return 'English';
  } else if (firstCharCode >= 0x4e00 && firstCharCode <= 0x9fff) {
    return 'Chinese';
  } else {
    return 'Unknown';
  }
}

async function translate(lang, text) {
  if (lang === "Chinese") {
    // res = "Hello" + text; // 翻译
    msg = [
      {
        role: "system",
        content: "You are a helpful assistant that translates Chinese to English."
      },
      {
        role: "user",
        content: `Translate the following Chinese text to English: ${text}`,
      }
    ]
  } else if (lang === "English") {
    // res = "你好" + text; // 翻译
    msg = [
      {
        role: "system",
        content: "You are a helpful assistant that translates English to Chinese."
      },
      {
        role: "user",
        content: `Translate the following English text to Chinese: ${text}`,
      }
    ]
  }
  const completion = await openai.createChatCompletion({
    model: "gpt-3.5-turbo",
    messages: msg
  });

  // console.log(completion)
  console.log(completion.data.choices[0].message.content);
  return completion.data.choices[0].message.content.replace(/^"(.*)"$/, '$1');
}

async function conversation(params){
  msg = [
    {
      role: "system",
      content: "I want you to act as a spoken English teacher and improver. I will speak to you in English and you will reply to me in English to practice my spoken English. I want you to keep your reply neat, limiting the reply to 100 words. I want you to strictly correct my grammar mistakes, typos, and factual errors. I want you to ask me a question in your reply. Now let's start practicing, you could ask me a question first. Remember, I want you to strictly correct my grammar mistakes, typos, and factual errors.",
    },
    {
      role: "user",
      content:text,
    },
  ];

   const completion = await openai.createChatCompletion({
     model: "gpt-3.5-turbo",
     messages: msg
  });

// console.log(completion)
console.log(completion.data.choices[0].message.content);
return completion.data.choices[0].message.content.replace(/^"(.*)"$/, '$1');
}

**Comment by Dada01Github** [comment]
用 const { BlazeClient } = require("mixin-node-sdk") 替换图中红框代码
![image](https://user-images.githubusercontent.com/125847418/233035155-7186526a-c210-403d-93c0-2028f17aecf3.png)

**Comment by AndyZhou6688** [comment]
感谢战友解答，已解决。
