### ISSUE TITLE
0-4.使用 Oh My Zsh 官网提供的安装命令安装它失败：Failed to connect to raw.githubusercontent.com port 433...

### ISSUE THREAD

**Issue by LazzaroneS** [coding-newbies-group/programming-co_creation-docs#18]
- 系统：Mac OS
- 终端：iTerm
- 描述操作：使用 `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"` 安装 _Oh My Zsh_ 失败
- 报错：`curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 9 ms: Connection refused`
![failedToConnect](https://user-images.githubusercontent.com/41162617/220639415-2eb60a6c-6a39-4ec0-bf67-ab6fd49ab389.jpg)

**Comment by freefunfee7** [comment]
我用chatGPT查了下你这个问题，chatGPT反馈了我这几种解决方式，你也可以试试
![chatgpt-answer](https://user-images.githubusercontent.com/59427476/220829609-093ead27-a994-4018-8ccd-ac4da0338447.png)

我的判断：
（1）网络问题：你能否打开github网页；你可以搭梯子开vpn再试下
（2）用镜像：chatGPT提供的方案里有一个ohmyzsh的镜像源，使用镜像源的命令安装
sh -c "$(curl -fsSL https://gitee.com/mirrors/oh-my-zsh/raw/master/tools/install.sh)"
你再试试

**Comment by LazzaroneS** [comment]
@freefunfee7 感谢大佬，使用 Gitee 的镜像源搞定了。🙏

![OhMyZshInstalled](https://user-images.githubusercontent.com/41162617/220945198-4cd96245-d038-4d6d-92c4-7057f1353bc1.jpg)
