### ISSUE TITLE
英语助手：视频8 translate被反复调用，造成API访问受限

### ISSUE THREAD

**Issue by AndyZhou6688** [coding-newbies-group/programming-co_creation-docs#180]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：translate被反复调用，造成API访问受限
> 你的报错（提供报错）：
![cc70c6863c8eb4c4080528c3f4372d5](https://user-images.githubusercontent.com/85618947/234470729-2dee91d5-c18c-4736-b10b-a2b674813b84.png)
![6e3823c927c2443fc0d834a071f9558](https://user-images.githubusercontent.com/85618947/234470745-2bc51d71-e412-4aa5-bb33-5031cf12b90c.png)

// Mix Bot
const { BlazeClient } = require('mixin-node-sdk');
const config = require("./config");
const client = new BlazeClient(
  {
    pin: config.pin,
    client_id: config.client_id,
    session_id: config.session_id,
    pin_token: config.pin_token,
    private_key: config.private_key
  },
  { parse: true, syncAck: true }
);

// ChatGPT
const { Configuration, OpenAIApi } = require("openai");
const configuration = new Configuration({
  apiKey: config.openai_key,
});
const openai = new OpenAIApi(configuration);

// WebSocket
client.loopBlaze({
  async onMessage(msg) {
    console.log(msg);
    if (msg.category === "PLAIN_TEXT") {
      const rawData = msg.data.toString();

      const lang = checkLanguage(rawData)

      let rawZhData = "";
      let rawEnData = "";
      let cost = 0
      console.log(cost);

      if (lang === "Chinese") {
        console.log("Chinese");
        rawZhData = rawData;//中文
        rawEnData = (await translate(lang, rawData)).res;//英文
        cost += (await translate(lang, rawData)).cost;
        console.log(cost);
      } else if (lang === "English") {
        console.log("English");
        rawEnData = rawData;//英文
        rawZhData = (await translate(lang, rawData)).res;//中文
        cost += (await translate(lang, rawData)).cost;
        console.log(cost);
      } else if (lang === "Unknown") {
        console.log("Unknown");
        client.sendMessageText(
          msg.user_id,
          'Only English and Chinese are supported.\n仅支持英文或中文。'
        );
      }
      // 处理收到的消息

      //处理返回的消息
      const returnEnData = await conversation(rawEnData).res;//英文
      cost += (await conversation(lang, rawEnData)).cost;
      console.log(cost);
      const returnZhData = await translate("English", returnEnData).res;//中文
      cost += (await translate(lang, rawData)).cost;

      console.log(cost);

      const res = `> 用户\n英文：${rawEnData}\n中文：${rawZhData}\n\n< 助手：\n英文：${returnEnData}\n中文：${returnZhData}`;

      client.sendMessageText(msg.user_id, res);
    } else {
      client.sendMessageText(msg.user_id, "Plain text only.\n仅支持文本。")
    }
  },
  onAckReceipt() { },
});

// Functions
function checkLanguage(text) {
  const firstCharCode = text.charCodeAt(0);
  if (firstCharCode >= 0x0000 && firstCharCode <= 0x007F) {
    return 'English';
  } else if (firstCharCode >= 0x4e00 && firstCharCode <= 0x9fff) {
    return 'Chinese';
  } else {
    return 'Unknown';
  }
}

async function translate(lang, text) {
  if (lang === "Chinese") {
    // res = "Hello" + text; // 翻译
    msg = [
      {
        role: "system",
        content: "You are a helpful assistant that translates Chinese to English."
      },
      {
        role: "user",
        content: `Translate the following Chinese text to English: ${text}`,
      }
    ]
  } else if (lang === "English") {
    // res = "你好" + text; // 翻译
    msg = [
      {
        role: "system",
        content: "You are a helpful assistant that translates English to Chinese."
      },
      {
        role: "user",
        content: `Translate the following English text to Chinese: ${text}`,
      }
    ]
  }

  const res = (await queryChatGPT(msg)).res;
  const token = (await queryChatGPT(msg)).token;
  const costs = await cost(token);
  return { res: res, cost: costs };
}

async function conversation(text) {
  msg = [
    {
      role: "system",
      content: "I want you to act as a spoken English teacher and improver. I will speak to you in English and you will reply to me in English to practice my spoken English. I want you to keep your reply neat, limiting the reply to 100 words. I want you to strictly correct my grammar mistakes, typos, and factual errors. I want you to ask me a question in your reply. Now let's start practicing, you could ask me a question first. Remember, I want you to strictly correct my grammar mistakes, typos, and factual errors.",
    },
    {
      role: "user",
      content: text,
    },
  ];
  const res = (await queryChatGPT(msg)).res;
  const token = (await queryChatGPT(msg)).token;
  const costs = cost(token);
  return { res: res, cost: costs };
}

// //设置等待时间
// async function GPT(msg) {
//   await sleep(15000);
//   const result = await queryChatGPT(msg);
//   return result;
// }

// function sleep(ms) {
//   return new Promise(resolve => setTimeout(resolve, ms));
// }

async function queryChatGPT(msg) {
  const completion = await openai.createChatCompletion({
    model: "gpt-3.5-turbo",
    messages: msg
  });

  // console.log(completion)
  console.log(completion.data.choices[0].message.content.replace(/^"(.*)"$/, '$1'));
  console.log(completion.data.usage.total_tokens);
  const res = completion.data.choices[0].message.content.replace(/^"(.*)"$/, '$1');
  const token = completion.data.usage.total_tokens;
  return { res: res, token: token };
}

async function cost(token) {
  const cost = 0.222 / 1000 * token
  return cost
}

// console.log(completion.data.choices[0].message.content).replace(/^"(.*)"$/, '$1');
//   console.log(completion.data.usage.total_tokens);
//   const res = completion.data.choices[0].message.content.replace(/^"(.*)"$/, '$1');
//   const token = completion.data.usage.total_tokens;
//   return {res: res, token: token};

**Comment by AndyZhou6688** [comment]
代码改成这样，还是不行：
// Mix Bot
const { BlazeClient } = require('mixin-node-sdk');
const config = require("./config");
const client = new BlazeClient(
  {
    pin: config.pin,
    client_id: config.client_id,
    session_id: config.session_id,
    pin_token: config.pin_token,
    private_key: config.private_key
  },
  { parse: true, syncAck: true }
);

// ChatGPT
const { Configuration, OpenAIApi } = require("openai");
const configuration = new Configuration({
  apiKey: config.openai_key,
});
const openai = new OpenAIApi(configuration);

// WebSocket
client.loopBlaze({
  async onMessage(msg) {
    console.log(msg);
    if (msg.category === "PLAIN_TEXT") {
      const rawData = msg.data.toString();
      const lang = checkLanguage(rawData)

      let rawZhData = "";
      let rawEnData = "";
      let cost = 0
      console.log(cost);

      if (lang === "Chinese") {
        console.log("Chinese");
        rawZhData = rawData;//中文
        rawEnData = (await translate(lang, rawData)).res;//英文
        cost += (await translate(lang, rawData)).cost;
        console.log(cost);
      } else if (lang === "English") {
        console.log("English");
        rawEnData = rawData;//英文
        rawZhData = (await translate(lang, rawData)).res;//中文
        cost += (await translate(lang, rawData)).cost;
        console.log(cost);
      } else if (lang === "Unknown") {
        console.log("Unknown");
        client.sendMessageText(
          msg.user_id,
          'Only English and Chinese are supported.\n仅支持英文或中文。'
        );
      }
      // 处理收到的消息

      //处理返回的消息
      console.log(rawEnData);
      const returnEnData = await conversation(rawEnData).res;//英文
      cost += (await conversation(lang, rawEnData)).cost;
      console.log(cost);
      const returnZhData = await translate("English", returnEnData).res;//中文
      cost += (await translate(lang, rawData)).cost;

      console.log(cost);

      const res = `> 用户\n英文：${rawEnData}\n中文：${rawZhData}\n\n< 助手：\n英文：${returnEnData}\n中文：${returnZhData}`;
      await client.sendMessageText(msg.user_id, res);
    } else {
      client.sendMessageText(msg.user_id, "Plain text only.\n仅支持文本。")
    }
  },
  onAckReceipt() { },
});

// Functions
async function cost(token) {
  const cost = (0.002 / 1000) * token;
  return cost
}

function checkLanguage(text) {
  const firstCharCode = text.charCodeAt(0);
  if (firstCharCode >= 0x0000 && firstCharCode <= 0x007F) {
    return 'English';
  } else if (firstCharCode >= 0x4e00 && firstCharCode <= 0x9fff) {
    return 'Chinese';
  } else {
    return 'Unknown';
  }
}

async function translate(lang, text) {
  if (lang === "Chinese") {
    // res = "Hello" + text; // 翻译
    msg = [
      {
        role: "system",
        content: "You are a helpful assistant that translates Chinese to English.",
      },
      {
        role: "user",
        content: `Translate the following Chinese text to English: ${text}`,
      },
    ];
  } else if (lang === "English") {
    // res = "你好" + text; // 翻译
    msg = [
      {
        role: "system",
        content: "You are a helpful assistant that translates English to Chinese.",
      },
      {
        role: "user",
        content: `Translate the following English text to Chinese: ${text}`,
      },
    ];
  }

  const res = (await queryChatGPT(msg)).res;
  const token = (await queryChatGPT(msg)).token;
  const costs = await cost(token);
  return { res: res, cost: costs };
}

async function conversation(text) {
  msg = [
    {
      role: "system",
      content: "I want you to act as a spoken English teacher and improver. I will speak to you in English and you will reply to me in English to practice my spoken English. I want you to keep your reply neat, limiting the reply to 100 words. I want you to strictly correct my grammar mistakes, typos, and factual errors. I want you to ask me a question in your reply. Now let's start practicing, you could ask me a question first. Remember, I want you to strictly correct my grammar mistakes, typos, and factual errors.",
    },
    {
      role: "user",
      content: text,
    },
  ];
  const res = (await queryChatGPT(msg)).res;
  console.log(res);
  const token = (await queryChatGPT(msg)).token;
  console.log(token);
  const costs = await cost(token);
  console.log("costs:"+costs)
  return { res: res, cost: costs };
}

// //设置等待时间
// async function GPT(msg) {
//   await sleep(15000);
//   const result = await queryChatGPT(msg);
//   return result;
// }

// function sleep(ms) {
//   return new Promise(resolve => setTimeout(resolve, ms));
// }

async function queryChatGPT(msg) {
  const completion = await openai.createChatCompletion({
    model: "gpt-3.5-turbo",
    messages: msg,
  });
  const res = completion.data.choices[0].message.content.replace(/^"(.*)"$/, '$1');
  const token = completion.data.usage.total_tokens;
  return { res: res, token: token };
}



// console.log(completion.data.choices[0].message.content).replace(/^"(.*)"$/, '$1');
//   console.log(completion.data.usage.total_tokens);
//   const res = completion.data.choices[0].message.content.replace(/^"(.*)"$/, '$1');
//   const token = completion.data.usage.total_tokens;
//   return {res: res, token: token};

**Comment by cxiaoxiong** [comment]
我也遇到类似的问题，请教了大强和放鹅娃战友后，解决方法如下：

1.先把调用的OpenAI 的API 的代码注释掉；

2.运行没有调用 OpenAI的代码，且能正常运行，把之前发给机器人的消息清空；

3.加上一个 ` sleep() ` 函数，因为 API的调用每分钟3次，这里设置20的暂停时间。

```javascript
async function GPT(msg){
    await sleep(15000);
    const result = await queryChatGPT(msg);
    return result;
  }
  
  function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
```

**Comment by AndyZhou6688** [comment]
谢谢小熊同学~
