### ISSUE TITLE
英语小助手：视频14-15获取音频部分await getAudio(url)和await getAudio(url, filename);

### ISSUE THREAD

**Issue by AndyZhou6688** [coding-newbies-group/programming-co_creation-docs#187]
> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：视频14-15获取音频部分await getAudio(url)和await getAudio(url, filename)，把(url)改成(url, filename)的原因是什么？
> 你的报错（提供报错）：视频14第146行代码是await getAudio(url)，视频15第44行代码是await getAudio(url, filename)，但是视频中没有这段代码的修改记录，请问这样修改的原因和目的是什么？
![2](https://user-images.githubusercontent.com/85618947/236594641-ebfdf124-28e5-4215-92e5-2a310ef04864.png)
![1](https://user-images.githubusercontent.com/85618947/236594644-1d23af4f-dd85-47a3-96f1-a685315011d2.png)

**Comment by vwumumu** [comment]
原因是，一开始以为url中filename固定从52位开始，后来发现有例外的情况。
所以，后面改成了，先把filename通过正则表达式取了出来，而不是通过substring取固定位置后面的内容作为filename。

**Comment by AndyZhou6688** [comment]
明白了，感谢解答~
