### ISSUE TITLE
powershell在电脑上没有，在那可下载安装?

### ISSUE THREAD

**Issue by Dg13580709178** [coding-newbies-group/programming-co_creation-docs#19]
powershell在电脑上没有，在那可下载安装?谢谢战友回复

**Comment by Dg13580709178** [comment]
http://www.downza.cn/soft/299662.html  通过查找，可在这网站下载，哈哈

**Comment by Fangewa** [comment]
李骏老师的课程里面有
https://github.com/neolee/pilot/blob/master/x1-setup.md

**Comment by Fangewa** [comment]
如果是Windows系统，直接win+r
输入powershell就打开了
