### ISSUE TITLE
配置SSH，使用Powerpoint受阻

### ISSUE THREAD

**Issue by fangfeng-0214** [coding-newbies-group/programming-co_creation-docs#20]
> 系统：Windows10
> 编译器：VSCode
> Python版本：3.8.2
![image](https://user-images.githubusercontent.com/68979481/220662408-11192ea9-c476-4177-9955-97c3581e25f9.png)

**Comment by fangfeng-0214** [comment]
上面的问题是否是因为 '$' 与‘ssh-keygen -t ed25519 -C‘ 之间的空格导致
但下面的尝试又出现如下问题：
![image](https://user-images.githubusercontent.com/68979481/220801379-42a57df5-4058-474d-84bd-a1a14ea75049.png)

**Comment by vwumumu** [comment]
去掉$符号，命令应该是：ssh-keygen -t ed25519 -C “jane102889@126.com”

**Comment by fangfeng-0214** [comment]
#0-3为github配置ssh的问题不知道问题在哪

打开PowerShell编译器（不确定这样说对不对），把上面的代码复制黏贴，得到的结果如下图。

对于小白来说，真是一个小台阶就是上不去。

![image](https://user-images.githubusercontent.com/68979481/220940065-2ff10dd0-7484-44d8-8263-a49e0f08fda3.png)

**Comment by pyz610173878** [comment]
不知道该如何定位问题

**Comment by pyz610173878** [comment]
1. 你先通过 `ssh-V`验证一下是不是存在客户端。如果是存在可能没有添加到环境变量。

第二种办法，你也可以打开 git bash客户端，git内置了ssh。

**Comment by fangfeng-0214** [comment]
＃　完成ｓｓｈ配置
去掉$符号，命令应该是：ssh-keygen -t ed25519 -C “[jane102889@126.com](mailto:jane102889@126.com)”

老师，我最后配置时，是邮箱两边的引号没有加做成功的，是否：邮箱用引号或不用都可以

按照楼上战友的建议用 ssh -V验证了，现在我的配置应该是成功了吧

谢谢大家的支持、帮助
![image](https://user-images.githubusercontent.com/68979481/221326437-cdf51312-4677-47dc-bbfc-908ffb43156d.png)

**Comment by fangfeng-0214** [comment]
＃　为啥我楼上的标题用了加空格之后，没有以标题的形式展示，似乎此刻我的输入模式改变了，明明是半角英语模式下，输入的字母和数字都是全角展示ｚｚ
