### ISSUE TITLE
0-5.通过Github共创：执行code .报错

### ISSUE THREAD

**Issue by DSH5200** [coding-newbies-group/programming-co_creation-docs#23]
> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：在programming-co_creation-docs路径下执行code .
> 你的报错（提供报错）：
![image](https://user-images.githubusercontent.com/125792779/220928777-9a2f1268-55e0-4479-9644-c6c7cd077254.png)

**Comment by vwumumu** [comment]
没有进入“programming-co_creation-docs”这个路径，现在是在windows\system32这个路径。
这个问题的原因在于对命令行路径的理解，会作为典型错误补充道命令行相关材料中。

**Comment by vwumumu** [comment]
可以再观察一下 **下图** 教材中的路径和你的路径有什么区别？
然后回顾一下[4.使用命令行](https://coding-newbies-group.github.io/programming-co_creation-docs/docs/p0/p0-4-cli)，
- 什么是路径分隔符？
- 如何切换到目录：“programming-co_creation-docs”？
- 如何查看当前目录？
![image](https://user-images.githubusercontent.com/81784095/220974535-4936bf99-872f-4f62-a934-c30cc232d9c6.png)

**Comment by LazzaroneS** [comment]
之所以会遇到类似的问题，可能就是这三个问题没思考清楚：
> - 什么是路径分隔符？
> - 如何切目录？
> - 如何查看当前目录？

弄了一个视频，视图做一些剖析和阐释。
> 视频：[如何通过命令行进入一个目录？](https://www.bilibili.com/video/BV18v4y1e7QD/?vd_source=08ffb5056ed58860f28c643cbea98c2d)

**Comment by DSH5200** [comment]
> 之所以会遇到类似的问题，可能就是这三个问题没思考清楚：
> 
> > * 什么是路径分隔符？
> > * 如何切目录？
> > * 如何查看当前目录？
> 
> 弄了一个视频，视图做一些剖析和阐释。
> 
> > 视频：[如何通过命令行进入一个目录？](https://www.bilibili.com/video/BV18v4y1e7QD/?vd_source=08ffb5056ed58860f28c643cbea98c2d)

谢谢指点

**Comment by DSH5200** [comment]
> 可以再观察一下 **下图** 教材中的路径和你的路径有什么区别？ 然后回顾一下[4.使用命令行](https://coding-newbies-group.github.io/programming-co_creation-docs/docs/p0/p0-4-cli)，
> 
> * 什么是路径分隔符？
> * 如何切换到目录：“programming-co_creation-docs”？
> * 如何查看当前目录？
>   ![image](https://user-images.githubusercontent.com/81784095/220974535-4936bf99-872f-4f62-a934-c30cc232d9c6.png)

谢谢大佬

**Comment by vwumumu** [comment]
@DSH5200 如果您的问题解决了，请关闭Issues，如果对于这个问题还没有解决，麻烦继续提问，咱一起把问题解决掉。

**Comment by just-createone** [comment]
> > 你的代码（描述操作）：在programming-co_creation-docs路径下执行code .
切换路径，原来的路径是windows\system32这个路径，要切换到programming-co_creation-docs这个路径，再去执行code.
战友可以看一下>共创文档准备篇第四节的视频。
