### ISSUE TITLE
Oh My Zsh 安装后关于修改配置没有整明白，是怎么进入配置界面的？

### ISSUE THREAD

**Issue by wangjinghao1123** [coding-newbies-group/programming-co_creation-docs#29]
> 系统：Mac
> 编译器：Jupyter Lab
> Python版本：3.11.2
> 你的代码（描述操作）：Oh My Zsh 安装后后面两幅图片——应该是关于配置的，但是没看懂——1、不知道怎么进入配置界面，进行配置。2、也不清楚这个这是做什么用的？3、我以为还是终端，但输入Python后并没有运行Python。
> 你的报错（提供报错）：
>
> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> 
<img width="247" alt="截屏2023-02-25 11 48 46" src="https://user-images.githubusercontent.com/83558176/221334633-8a115b6d-aacb-41a8-ac0b-3e011236e53e.png">

**Comment by wangjinghao1123** [comment]
我理解没错的话应该是优化后的终端，但是为什么，以前在终端直接输入Python就能进入交互界面，现在输入后回答的是zsh: command not found: python。

**Comment by pyz610173878** [comment]
你贴出来的命令行貌似是 git 命令行界面，有可能是这个原因。

可以先不管其原理，先开始学。这是笑来老师在自学是门手一中，提出的建议。

**Comment by wangjinghao1123** [comment]
我装了Oh My Zsh后命令界面就变成了这样，现在反倒不知道怎么从命令进入Python交互界面了。

**Comment by freefunfee7** [comment]
> 我装了Oh My Zsh后命令界面就变成了这样，现在反倒不知道怎么从命令进入Python交互界面了。

在安装了Oh My Zsh后，在命令行输入python，jupyter等命令出现没有找到相关命令的提示时，可能是因为~/.zshrc这个配置文件里没有export对应命令的路径
而在未安装Oh My Zsh前，你的命令是使用正常的话，可能之前命令行使用的是bash，对应的配置文件就是~/.bash_profile
现在你安装了Oh My Zsh后，你如果希望用到之前的命令，可以在~/.zshrc里添加 source ~/.bash_profile这条语句。这条语句的作用是使得在~/.bash_profile的配置内容生效
~/.zshrc里添加 source ~/.bash_profile这条语句后，再回到命令行执行source ~/.zshrc使这个配置生效
这样你再使用python，jupyter等命令，再看下是否能正常使用了

**Comment by niuniu132** [comment]
你print的是字符串还是变量，如果是字符串应该这样
print(“Hello Python”)

**Comment by vwumumu** [comment]
@wangjinghao1123 这个issues可以close了吗？
