### ISSUE TITLE
0-5：通过github共创-执行git commit -m 'update intro.md'命令无法对存档进行说明

### ISSUE THREAD

**Issue by DSH5200** [coding-newbies-group/programming-co_creation-docs#37]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：执行git commit -m 'update intro.md'命令
> 你的报错（提供报错）：无法对存档进行说明
![image](https://user-images.githubusercontent.com/125792779/221364721-024d8242-7278-49a6-a85b-2d1be7859eff.png)
我看教程上和视频上出来的是另外一种
![image](https://user-images.githubusercontent.com/125792779/221364868-1b2beb2a-a49a-4153-b1c8-a6b99f3e6847.png)

**Comment by just-createone** [comment]
> **Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**
> 
> > 系统：Windows11
> > 编译器：VSCode
> > Python版本：3.11.2
> > 你的代码（描述操作）：执行git commit -m 'update intro.md'命令
> > 你的报错（提供报错）：无法对存档进行说明
> > ![image](https://user-images.githubusercontent.com/125792779/221364721-024d8242-7278-49a6-a85b-2d1be7859eff.png)
> > 我看教程上和视频上出来的是另外一种
> > ![image](https://user-images.githubusercontent.com/125792779/221364868-1b2beb2a-a49a-4153-b1c8-a6b99f3e6847.png)

这个问题我遇到过，图片中的提示信息有看到吗？上面写着
**Please tell me who you are**,Run **git config --global user.email "you@example.com"**和下一行的代码（Run下面有两行代码）
我的解决方式是执行这两行代码中的一个，我执行的是第一个，即输入自己的邮箱地址，然后就成功push了。
战友也可以看看关掉的issues，和你是相同的问题。

**Comment by DSH5200** [comment]
> > **Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**
> > > 系统：Windows11
> > > 编译器：VSCode
> > > Python版本：3.11.2
> > > 你的代码（描述操作）：执行git commit -m 'update intro.md'命令
> > > 你的报错（提供报错）：无法对存档进行说明
> > > ![image](https://user-images.githubusercontent.com/125792779/221364721-024d8242-7278-49a6-a85b-2d1be7859eff.png)
> > > 我看教程上和视频上出来的是另外一种
> > > ![image](https://user-images.githubusercontent.com/125792779/221364868-1b2beb2a-a49a-4153-b1c8-a6b99f3e6847.png)
> 
> 这个问题我遇到过，图片中的提示信息有看到吗？上面写着 **Please tell me who you are**,Run **git config --global user.email "[you@example.com](mailto:you@example.com)"**和下一行的代码（Run下面有两行代码） 我的解决方式是执行这两行代码中的一个，我执行的是第一个，即输入自己的邮箱地址（输入的位置在引号里面），然后就成功push了。 战友也可以看看关掉的issues，和你是相同的问题。

谢谢战友指点。
