### ISSUE TITLE
0-5.通过 Github 共创：7.将自己的修改提交到共学共创仓库（Pull Request）

### ISSUE THREAD

**Issue by just-createone** [coding-newbies-group/programming-co_creation-docs#40]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：
> 你的报错（提供报错）：提交pull request出现conflict，不确定是否是成功了，也不知道成功了的界面应该是什么样的
![image](https://user-images.githubusercontent.com/69511529/221388728-7796af5f-9a95-4571-9573-41e45424dd9c.png)

**Comment by DSH5200** [comment]
成功的PR界面是这样的
![image](https://user-images.githubusercontent.com/125792779/221391626-250a7e5c-214f-4add-b46c-7910cb0d94ec.png)
你这个应该是成功的，我的也有conficting files.我看MIXIN群里面之前有人分享过，也是这样的：
![image](https://user-images.githubusercontent.com/125792779/221391668-3abac55d-273e-49a0-961d-e1f4db9b0de2.png)

**Comment by DSH5200** [comment]
你打开自己的github仓库，然后打开docs文件夹，看最下面test或者intro.md,用vscode或者typora打开，就能看到你刚更改的信息。如果你看到的信息就是你刚刚更改的，那就是PR成功了

**Comment by just-createone** [comment]
> 你打开自己的github仓库，然后打开docs文件夹，看最下面test或者intro.md,用vscode或者typora打开，就能看到你刚更改的信息。如果你看到的信息就是你刚刚更改的，那就是PR成功了

感谢战友解答，我自己的github仓库信息是更新了的，但是github仓库信息的更新只与push是否成功有关，简单来说就是我自己github仓库信息更新只能证明我在**git push**这一步是成功的，但是我的问题是想知道我的**pull request**这一步是否成功，以及想确认一下出现上述界面中conflict情况是否是因为他人和我修改同一分支所导致的，不知道是不是我哪里没有理解呢？

**Comment by just-createone** [comment]
问题已解决，在网上搜索发现，产生冲突的原因和我预想的一致，是因为多人同时修改同一个分支所导致的。

**Comment by just-createone** [comment]
> 问题已解决，在网上搜索发现，产生冲突的原因和我预想的一致，是因为多人同时修改同一个分支所导致的。

更正解答，产生冲突的原因是因为在pull request的时候原仓库内容发生了变更，所以会有冲突，而不是所谓的多人修改同一个分支造成的。
