### ISSUE TITLE
主仓库programming-co_creation-docs发生修改后（例如，增加了“笔记”模块），自己的github以及本地文件夹如何同步？

### ISSUE THREAD

**Issue by AndyZhou6688** [coding-newbies-group/programming-co_creation-docs#46]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：近期主仓库programming-co_creation-docs发生更新，新增加了“笔记”模块，但是之前fork进自己github仓库的内容未发生变化，请问自己的github仓库的项目如何更新，以及已经下载到本地的项目文件夹如何同步？

**Comment by RunJavaCode** [comment]
## 更新自己 fork 的仓库
Step 1：登陆 Github 仓库，找到 fork 到自己账户的仓库，
Step 2：找到 Sync fork 按钮，点击同步即可。

![image](https://user-images.githubusercontent.com/43558972/222021601-125a56e8-9275-483b-81cf-1b8631f3f742.png)

## 更新自己的本地仓库
找到自己本地 clone 下来的项目文件夹，使用下面的命令即可将本地仓库的内容与远程 fork 的仓库保持同步。
```
git pull
```
> 注意：使用 git pull 之前，要确保本地没有文件改动。如果有改动，需要先将改动 commit。否则会提示 git pull 失败。

如下图所示，第一次 `git pull` 提示本次拉取了远程 fork 仓库的所有更新，第二次 `git pull` 提示你本地仓库已经是最新的了，没有可以从远程 fork 仓库拉取的更新。

<img width="648" alt="image" src="https://user-images.githubusercontent.com/43558972/222022495-45c91826-3884-4cac-9d1c-942d17480e80.png">

**Comment by just-createone** [comment]
> ## 更新自己 fork 的仓库
> Step 1：登陆 Github 仓库，找到 fork 到自己账户的仓库， Step 2：找到 Sync fork 按钮，点击同步即可。
> 
> ![image](https://user-images.githubusercontent.com/43558972/222021601-125a56e8-9275-483b-81cf-1b8631f3f742.png)
> 
> ## 更新自己的本地仓库
> 找到自己本地 clone 下来的项目文件夹，使用下面的命令即可将本地仓库的内容与远程 fork 的仓库保持同步。
> 
> ```
> git pull
> ```
> 
> > 注意：使用 git pull 之前，要确保本地没有文件改动。如果有改动，需要先将改动 commit。否则会提示 git pull 失败。
> 
> 如下图所示，第一次 `git pull` 提示本次拉取了远程 fork 仓库的所有更新，第二次 `git pull` 提示你本地仓库已经是最新的了，没有可以从远程 fork 仓库拉取的更新。
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/43558972/222022495-45c91826-3884-4cac-9d1c-942d17480e80.png">

请问git commit这个操作是什么意思呢？如果不想保留自己本地的修改，直接pull，需要什么样的操作，执行什么样的命令？

**Comment by just-createone** [comment]
> ## 更新自己 fork 的仓库
> Step 1：登陆 Github 仓库，找到 fork 到自己账户的仓库， Step 2：找到 Sync fork 按钮，点击同步即可。
> 
> ![image](https://user-images.githubusercontent.com/43558972/222021601-125a56e8-9275-483b-81cf-1b8631f3f742.png)
> 
> ## 更新自己的本地仓库
> 找到自己本地 clone 下来的项目文件夹，使用下面的命令即可将本地仓库的内容与远程 fork 的仓库保持同步。
> 
> ```
> git pull
> ```
> 
> > 注意：使用 git pull 之前，要确保本地没有文件改动。如果有改动，需要先将改动 commit。否则会提示 git pull 失败。
> 
> 如下图所示，第一次 `git pull` 提示本次拉取了远程 fork 仓库的所有更新，第二次 `git pull` 提示你本地仓库已经是最新的了，没有可以从远程 fork 仓库拉取的更新。
> 
> <img alt="image" width="648" src="https://user-images.githubusercontent.com/43558972/222022495-45c91826-3884-4cac-9d1c-942d17480e80.png">

![image](https://user-images.githubusercontent.com/69511529/222602664-cd36c458-7fbf-442c-8043-cb5e0d406c5b.png)
我先是执行了git commit，然后再执行git pull，但是好像没有成功，请问战友图中这样的情况该怎么处理呢？

**Comment by RunJavaCode** [comment]
> > ## 更新自己 fork 的仓库
> > Step 1：登陆 Github 仓库，找到 fork 到自己账户的仓库， Step 2：找到 Sync fork 按钮，点击同步即可。
> > ![image](https://user-images.githubusercontent.com/43558972/222021601-125a56e8-9275-483b-81cf-1b8631f3f742.png)
> > ## 更新自己的本地仓库
> > 找到自己本地 clone 下来的项目文件夹，使用下面的命令即可将本地仓库的内容与远程 fork 的仓库保持同步。
> > ```
> > git pull
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > 注意：使用 git pull 之前，要确保本地没有文件改动。如果有改动，需要先将改动 commit。否则会提示 git pull 失败。
> > 
> > 
> > 如下图所示，第一次 `git pull` 提示本次拉取了远程 fork 仓库的所有更新，第二次 `git pull` 提示你本地仓库已经是最新的了，没有可以从远程 fork 仓库拉取的更新。
> > <img alt="image" width="648" src="https://user-images.githubusercontent.com/43558972/222022495-45c91826-3884-4cac-9d1c-942d17480e80.png">
> 
> ![image](https://user-images.githubusercontent.com/69511529/222602664-cd36c458-7fbf-442c-8043-cb5e0d406c5b.png) 我先是执行了git commit，然后再执行git pull，但是好像没有成功，请问战友图中这样的情况该怎么处理呢？

![image](https://user-images.githubusercontent.com/43558972/222617407-54f2278d-d3e4-4acb-bf07-8c1139e09009.png)

> 说明：抱歉在先前的回复中，我遗漏了两个点：1、在`git commit`之前，需要先将本地文件的变动通过 `git add`命令操作一下。2、在`git pull`前，需要设置分支合并策略。

## 第一个方框
在上图中，我框出了第一个点，就是你执行 `git commit`命令之后的返回信息。
返回的提示信息翻译成中文大致意思是：
> 你的分支和 `main` 分支有了差异。（需要你处理，处理方法在下面👇）
> 你需要使用 `git pull` 将远程分支合并到你目前的分支中。
> 有一个文件（报红色的地方）需要通过 `git add` 命令放到暂存区，才能 `commit`。

这里的话，你可以先执行一次 `git add .` 命令（注意命令中最后的一个点，表示*所有*）将本地做的**所有修改**提交到***暂存区***，然后才能通过 `git commit` 命令将 `add` 后的修改 `commit`。

## 第二个方框
框出的第二个点，就是你执行 `git pull`命令之后的返回信息。
这个框中包含一个警告（warning）和一个错误（error），翻译成中文大意是：
> 警告里的信息：不鼓励没有指定如何协调分支差异策略的拉取操作（pull）。在你下次执行 pull 前，需要执行下面其中一个命令来指定策略。
> 错误里的信息：你本地中以下文件的修改将会被`merge`操作覆盖。请先在`merge`前将你的修改 `commit` 或者 `stash`。

这里的话，如果你本地有修改，你最好先通过 `git add .` 将所有的修改放到暂存区，然后，执行一次 `git commit`操作。

如果本地没有修改，那么在执行 `git pull` 之前，你需要执行一下 `git config pull.rebase false` （这是默认的分支合并策略）命令设置当前仓库的分支合并策略，或者执行 `git config --global pull.rebase false` 命令设置以后所有仓库的分支合并策略。

**Comment by AndyZhou6688** [comment]
谢谢战友解答
