### ISSUE TITLE
0-3.通过Github共创（新手非必须）  git 具体安装什么版本

### ISSUE THREAD

**Issue by skymapcn** [coding-newbies-group/programming-co_creation-docs#6]
> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：print("Hello Python")
> 你的报错（提供报错）：
>
> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```

**Comment by vwumumu** [comment]
@skymapcn 我觉得Git用哪个版本都可以，我使用的版本如下，如果没装，到官方下载最新版即可。
PS C:\Users\vwumumu> git -v
git version 2.38.1.windows.1

**Comment by skymapcn** [comment]
#感谢 @vwumumu
