### ISSUE TITLE
创建Mixin机器人:Usersg下面没有vwumumu这个文件，应如何处理好？

### ISSUE THREAD

**Issue by dgzbk790119** [coding-newbies-group/programming-co_creation-docs#66]
[创建Mixin机器人:Usersg下面没有vwumumu这个文件，应如何处理好？
![1678116821068](https://user-images.githubusercontent.com/120799913/223156555-8f4dea74-1735-4ca2-b2a5-058aae67c6e8.png)

**Comment by vwumumu** [comment]
c:\users\vwumumu是我的例子，教程中写的是当前目录，你在任何目录创建一个文件夹然后继续做就可以。

**Comment by dgzbk790119** [comment]
收到，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mumu Wu ***@***.***&gt;
发送时间: 2023年3月7日 06:59
收件人: coding-newbies-group/programming-co_creation-docs ***@***.***&gt;
抄送: 钟康 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[coding-newbies-group/programming-co_creation-docs] 创建Mixin机器人:Usersg下面没有vwumumu这个文件，应如何处理好？ (Issue #66)





 
c:\users\vwumumu是我的例子，教程中写的是当前目录，你在任何目录创建一个文件夹然后继续做就可以。
