### ISSUE TITLE
提交作业，可以看到吗

### ISSUE THREAD

**Issue by 17606346852** [coding-newbies-group/programming-co_creation-docs#67]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/77789025/223335269-bed439a5-51ee-445c-b8e9-3bed1793428a.png">

**Comment by DSH5200** [comment]
作业不是在这里提交的，请在对应的版块提交，谢谢。

**Comment by AndyZhou6688** [comment]
提交作业的方式：
1、点击Mumu教程中的作业提交链接，进入作业收集的issue，该issue的作者是Mumu
2、把页面拉到最下面，直到看到一个方框，把截图拖到那个方框中，点“comment”按钮
