### ISSUE TITLE
1-5.函数：作业：进一步理解处理过程和输出：return "Hi" 返回的 'Hi' 在VSCode中不显示？

### ISSUE THREAD

**Issue by v5368965** [coding-newbies-group/programming-co_creation-docs#68]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：macOS Venturo 版本13.2.1
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：

**为什么作业中这段代码在python和VSCode中显示的不太一样（return "Hi" 返回的 'Hi' 在VSCode中没有显示）？**

图1、在python中显示结果是4个 Hi （其中有一个是带单引号的 ’Hi‘ ）：

<img width="751" alt="截屏2023-03-08 10 47 15" src="https://user-images.githubusercontent.com/68183059/223609589-d77527c9-0c40-4061-a8e5-53973292d4fb.png">

图2、在VSCode中，运行这段同样的代码，显示结果却只有三个 Hi ：

<img width="1010" alt="截屏2023-03-08 10 42 33" src="https://user-images.githubusercontent.com/68183059/223610249-b0fd9f2a-c4f9-4eb8-9a77-7f58510fb06d.png">

PS：考虑到可能是VSCode的一种默认情况，但还是想请各位大佬给讲解一下，先谢谢了！

**Comment by LazzaroneS** [comment]
我觉得这应该是 REPL ( read-eval-print loop ) 和 IDE ( Integrated Development Environment ) 在输出设计上的差异。

至于设计者为什么要制造这种差异，我猜测可能是因为：
- 在 IDE 里面你的代码就明晃晃在那儿，哪个函数有没有返回值你看看代码就知道了；同时所有的执行过程都是在执行 `.py` 文件之前就已经写好了的，包括对函数调用的结果进一步怎么处理。所以重点可能在于做你在 `.py` 文件里让机器做的事，输出 `.py` 文件让机器输出的东西，没有必要关心中间的哪个函数执行有没有返回值。
- 而在 REPL 中，随着你输入的命令数量的增加，你之前定义的函数可能就到屏幕外面去了，没法一眼看到了。这时你再去调用它，如果「它有没有返回值」能够直接体现在结果中，就便于你下一步的操作。比如有返回值（return）的话，你就可以将函数执行的结果赋值给一个变量。

**Comment by v5368965** [comment]
哦哦，清楚了，感谢大佬答疑解惑！
