### ISSUE TITLE
VSCode中为什么“运行python文件”和“在交互窗口运行当前文件”，出来的结果不一样？

### ISSUE THREAD

**Issue by AndyZhou6688** [coding-newbies-group/programming-co_creation-docs#71]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.7.4
> 你的代码（描述操作）：type(42)
> 你的报错（提供报错）：
>
![问题1](https://user-images.githubusercontent.com/85618947/223648263-9d54fd9c-37d6-49ca-a565-15a23d766df2.png)

> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```

**Comment by Fangewa** [comment]
print(type(42))

**Comment by AndyZhou6688** [comment]
谢谢战友解答，请问为什么在交互界面不需要用print()函数？

**Comment by Dada01Github** [comment]
在交互界面中，输出的结果会直接显示在界面上，不需要用print()函数来打印输出。而在代码文件中，需要用print()函数来将结果打印输出到控制台或文件中。

**Comment by Dada01Github** [comment]
![image](https://user-images.githubusercontent.com/125847418/223954917-894c4484-2935-447d-9b22-722f707e17ce.png)
1-3 IDE 集成环境视频 11.15里有解释。
