### ISSUE TITLE
1-5 函数  如何在vscode中创建一个函数？

### ISSUE THREAD

**Issue by Zhangjuanlli** [coding-newbies-group/programming-co_creation-docs#76]
> 编译器：VSCode
>如何在vscode中创建一个函数？从POWERSHELL转换到vscode ，如何在vscode中新建文件，这里没有再细说如何做，但对小白来说，不知道如何操作，即使知道是前面的知识点没有真的弄明白，但还是不知道去哪去学习。

视频2:13时候，看花了眼，不明觉厉。

![image](https://user-images.githubusercontent.com/68979481/223735329-c9b2c20f-a00b-450b-ba7f-d476fbf63695.png)

**Comment by fangfeng-0214** [comment]
![image](https://user-images.githubusercontent.com/68979481/223741060-1aaf9672-c27f-43b6-86e2-9a1eaf12b0c3.png)
老师的输出结果是3，我点运行后，没有输出。这是什么原因。

**Comment by freefunfee7** [comment]
你这个代码没有问题，没有输出结果是3的可能原因是这个hellp Python.py文件你在新增代码后没有保存该文件。
你ctrl+s快捷键保存后，再运行下试试。

**Comment by Zhangjuanlli** [comment]
今天再次打开运行，获得期待中的结果3。
对照下图的输出情况，同样的代码类型，我以为应该输出2个3，两个结果不同的原因是什么？
![image](https://user-images.githubusercontent.com/68979481/224443216-f4623350-3781-4158-aad2-5e2a8abcc10a.png)

**Comment by xiong321123** [comment]
在这里面：
![image](https://user-images.githubusercontent.com/91486483/224459608-a041328d-b7bb-4afc-b937-2edbe1e6ad9b.png)
输出两个“Hi”，的原因是第5行a=lee()的过程就会执行函数Lee（）,执行print("Hi").打印大写的Hi，并将return的结果保存在a中
第6行只打印a保存的内容，即打印小写的hi。

![image](https://user-images.githubusercontent.com/91486483/224459898-15b830dc-732c-491d-bae0-1daacf0e860d.png)
在这里面，plus（）函数执行过程中不会有打印动作，只是将结果保存在sum中，直到第8行的print（sum），才会打印一次3.

**Comment by xiong321123** [comment]
![image](https://user-images.githubusercontent.com/91486483/224460151-24c59035-fa78-44de-b40e-1ad3772ed5e3.png)
如果将之前打印Hi程序里面的第6行：print(a)改成print(lee()),就会打印两个大写的Hi和一个小写的hi。原因是执行第5行a=lee()时，会运行lee()函数一次，打印一次Hi。执行第6行print（Lee())时，又会运行lee()函数一次，打印一次Hi，并将return的结果，小写的hi也打印一次。
不知道我有没有说清楚，你多试几次，体验一下呢

**Comment by LazzaroneS** [comment]
## 提炼问题

@Zhangjuanlli 我可能还是比较理解你的意思。因为之前我在接触现成的陌生代码时，也有不少类似的困惑：

**代码执行结果和猜想的不一样。**

## 怎么办？

### Ⅰ 我认为，首先要弄清楚什么是定义函数，什么是调用函数。

**定义函数**就是用代码说清楚这个函数是干嘛用的，它可以做什么。

在从前，人们做了一种容器，称它是尿壶，它可以让你在半夜内急时轻松解决问题。

**调用函数**就是之前定义好的函数，现在真正开始使用。

你在真正开始使用一个函数之前，得先定义好这个函数。当你半夜尿急了想要使用尿壶，首先你得先有一个尿壶对吧？

**所以，创造归创造，使用归使用。定义函数就是「创造」，调用函数就是「使用」。**

### Ⅱ 分享一个李俊老师分享过的自学方法，我用这个方法收获了很多：

> **修改代码，多做实验。**

来看看 puls 和 demo 这两个函数：

```python
def plus(input1, input2):
    return input1 + input2

sum = plus(1, 2)

print(sum)
```

```python
def demo():
    print("Hi")
    return "Hi"
```

可以看到，这两个函数定义的时候还是有一些差别的，plus 函数只有 return, 而 demo 函数有 print 和 return. 

然后，我们可能就会想了，是不是因为定义的差异导致了结果与猜想不同呢？我真的理解 print 和 return 具体是在干什么吗？

再然后，我们就可以动手做个实验来看看：

![printHi](https://user-images.githubusercontent.com/41162617/224464874-dbfd718d-1134-471b-9cc9-b49fde55d993.jpg)

![returnHi](https://user-images.githubusercontent.com/41162617/224464879-230f7bd7-bb0c-4b07-bd62-2980d0c51d97.jpg)

对比一下实验结果，至少就明白了，print 会输出到屏幕上，return 不会自动输出到屏幕上，对吧？又进步了一点点。

P.S. 不要想看微小的进步，相信“聚沙成塔”，身处定投课堂的我们不是看到了一个又一个大佬 Ta 们不就是这么变成厉害的大佬的吗？

**Comment by Zhangjuanlli** [comment]
感恩我们的共学共创，让我从开始的什么都不明白，到懵懂地有点明白，有些思考，有点尝试，进而得到大家的深入探讨，直至阿坦大佬说出的自身颇多受益的李骏老师的提醒：**修改代码，多做实验**，学习就是不断尝试，在探索中成长进步。
