### ISSUE TITLE
1-6.做个Mixin机器人:执行node index.js后报错，机器人没有回应

### ISSUE THREAD

**Issue by dgzbk790119** [coding-newbies-group/programming-co_creation-docs#77]
做个Mixin机器人:   4,让机器人动起来   在命令行中执行node index.js，光标会呈现一个闪烁的状态：但我的画面却出现这个：同时机器人问话后也不会回复。麻烦老师答复下我这个小白，实在无从下手才发出来，谢谢。
![1678284618811](https://user-images.githubusercontent.com/120799913/223737237-caafdbbc-1218-4fec-88e1-c7ad86ca688a.png)

**Comment by Ayan0217** [comment]
提示缺少右括号）
可以仔细再检查node index.js的代码看看有没有哪个位置缺少右括号），注意是英文状态的符号。
然后再试着运行一下

以上供参考

**Comment by AndyZhou6688** [comment]
![5](https://user-images.githubusercontent.com/85618947/223981793-1feb8f3a-189d-4a4e-9a02-d3e47a762db8.png)
检查下红框位置有没有少了“，”逗号。我第一次配置时，出现和您相同的情况，加“，”就好了

**Comment by Zhangjuanlli** [comment]
编程就是磨炼我们的观察能力，需要我们练就火眼金睛，正常的代码是干净工整的，而类似括号后面的小波浪划线，红颜色的小划线，都是提醒我们有问题 的地方，你在VScode里的代码就是复制时少了个“ ,”.
![image](https://user-images.githubusercontent.com/68979481/224697955-7268dbcd-ac7f-4d20-b443-24d9273f4cf1.png)
