### ISSUE TITLE
1-7逻辑判断与分支：TypeError: client.sendmessagetext is not a function

### ISSUE THREAD

**Issue by AndyZhou6688** [coding-newbies-group/programming-co_creation-docs#79]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.7.4
> 你的代码（描述操作）：TypeError: client.sendmessagetext is not a function
> 你的报错（提供报错）：
>
![1](https://user-images.githubusercontent.com/85618947/224248633-8cdf105a-b96a-44b2-a8d5-f17cf22a0d60.png)
![2](https://user-images.githubusercontent.com/85618947/224248684-ce6b3b6a-58ae-4293-a8c2-44ebd740bcab.png)
![3](https://user-images.githubusercontent.com/85618947/224248703-f09a3989-61a6-433c-be04-746bb4f2ffd0.png)

> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```

**Comment by Fangewa** [comment]
改成sendMessageText就好了，大写的M和T

**Comment by vwumumu** [comment]
别急，还没release

**Comment by AndyZhou6688** [comment]
> 

谢谢战友解答，改成大写的M和T就好了
