### ISSUE TITLE
0-2.Markdown超简教程: 改颜色

### ISSUE THREAD

**Issue by Fangewa** [coding-newbies-group/programming-co_creation-docs#8]
> 系统：Windows10
> 编译器：VSCode
> Python版本：3.11.0
> 你的代码（描述操作）：想改变Typora里面的字体和引用符号的颜色应该怎么操作？（尝试使用issues）

**Comment by vwumumu** [comment]
<font color="E71853">带颜色的字体</font>

**Comment by vwumumu** [comment]
我试了一下，Markdown支持，用法如下：但是Github Issues好像不支持，看看其他大佬是否知道
``` html
<font color="E71853">带颜色的字体</font>
```

**Comment by RunJavaCode** [comment]
可以通过写 HTML 标签的语法来实现对字体和引用符号的颜色进行自定义设置。不过这要求你必须懂点基本的 HTML 语法知识。

如果你也是使用 Typora 作为编辑 Markdown 的工具，那么以下 Typora 对 HTML 语法支持的链接，也许对你有用：

[HTML Support in Typora](https://support.typora.io/HTML/)

**Comment by Fangewa** [comment]
> 

太棒了，感谢~~

**Comment by Fangewa** [comment]
> 

好用，谢谢~~
