### ISSUE TITLE
3.IDE集成开发环境: vscode 中yuanxi完成作业内容 提示错误

### ISSUE THREAD

**Issue by skymapcn** [coding-newbies-group/programming-co_creation-docs#83]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：
运行代码时出错

> 你的报错（提供报错）：
<img width="690" alt="image" src="https://user-images.githubusercontent.com/29712741/224352561-6ef43478-0bd0-497a-8935-292dcfd987b4.png">

> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```

**Comment by AndyZhou6688** [comment]
在命令行输入：pip install ipython，然后看是否解决

**Comment by skymapcn** [comment]
谢谢回复。今天用vs code  做作业时已经不报错误。

**Comment by skymapcn** [comment]
> 在命令行输入：pip install ipython，然后看是否解决

请问一下 在那个路径下执行?
