### ISSUE TITLE
1-3.IDE集成开发环境   作业  ( wakatime Api Key)如何设置？

### ISSUE THREAD

**Issue by holtxu** [coding-newbies-group/programming-co_creation-docs#85]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows10
> 编译器：VSCode
> Python版本：3.10.6
> 你的代码（描述操作）：print(Hello Python)

![image](https://user-images.githubusercontent.com/125620704/224455453-990dd29a-b4e7-448c-8977-10641417c38c.png)

![image](https://user-images.githubusercontent.com/125620704/224455471-f4ddb729-615f-4679-824e-73227ff6f72c.png)

> 你的报错（提供报错）：

![image](https://user-images.githubusercontent.com/125620704/224455553-f0adebec-23aa-420d-aac3-c8c43a193cc5.png)

>
> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```

**Comment by holtxu** [comment]
WakaTime Api Key已设置好。

**Comment by AndyZhou6688** [comment]
![1](https://user-images.githubusercontent.com/85618947/224470422-f7d5cea6-b3c9-49b9-a36b-a0b2d6904989.png)
出现这个图标，说明您已经设置好了wakatime插件了
