### ISSUE TITLE
6.做个Mixin机器人: 1.2.安装Nodejs  时提示  不知道应该怎么下一步操作

### ISSUE THREAD

**Issue by skymapcn** [coding-newbies-group/programming-co_creation-docs#88]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：print(Hello Python)
> 你的报错（提供报错）：
>
> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```
<img width="679" alt="image" src="https://user-images.githubusercontent.com/29712741/224474118-50bc0c71-7938-49f3-aec8-daa2b4969d97.png">

**Comment by vwumumu** [comment]
点运行即可，这个意思是Windows希望用它的杀毒软件扫描此安装包，但是无法访问安全扫描的页面，我们是从Node官网下载的安装包，所以，点击运行即可。

**Comment by skymapcn** [comment]
收到，谢谢!
