### ISSUE TITLE
6.做个Mixin机器人  2.2.填写Mixin机器人信息   如何设置 首页网址、验证网址，因为是必填项 卡在这儿了

### ISSUE THREAD

**Issue by skymapcn** [coding-newbies-group/programming-co_creation-docs#89]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

<img width="656" alt="image" src="https://user-images.githubusercontent.com/29712741/224474329-bbb097bf-1b3e-4952-afff-248265f81bb1.png">

**Comment by vwumumu** [comment]
我会把一下内容更新至教程
![image](https://user-images.githubusercontent.com/81784095/224474759-30ceb8d1-4136-4ee4-b6ef-81689c8b80d9.png)

**Comment by skymapcn** [comment]
谢谢补充！
