### ISSUE TITLE
0-3.通过Github共创：配置SSH验证，eval "$(ssh-agent -s)" 命令不可用

### ISSUE THREAD

**Issue by Fangewa** [coding-newbies-group/programming-co_creation-docs#9]
> 系统：Windows10
> 编译器：VSCode
> Python版本：3.11.0
> 你的代码（描述操作）：eval "$(ssh-agent -s)"
> 你的报错（提供报错）：

PS C:\Users\Eric\.ssh> eval "$(ssh-agent -s)"
unable to start ssh-agent service, error :1058
eval : 无法将“eval”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ eval "$(ssh-agent -s)"
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (eval:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by vwumumu** [comment]
@Fangewa 已经有人提交windows ssh的pull request，请稍等。

**Comment by vwumumu** [comment]
@Fangewa https://www.bilibili.com/video/BV1S54y1w7XN/?vd_source=4a888db8814702b2062fcaf2575be745
我写了新的教程，看看能否解决你的问题。

**Comment by LazzaroneS** [comment]
@Fangewa  抱歉，之前的写的文档确实没有做好测试验证工作。文档 @vwumumu  已经修订，不需要再使用 `eval "$(ssh-agent -s)"` 命令。

文档入口：[为 Github 配置 SSH 登录（Windows）](
https://coding-newbies-group.github.io/programming-co_creation-docs/docs/p0/p0-5-collaborate#2%E4%B8%BAgithub%E9%85%8D%E7%BD%AEssh%E7%99%BB%E5%BD%95)

**Comment by Fangewa** [comment]
Done!
