### ISSUE TITLE
编程作业提交指南：上传图片失败。错误信息: {"success":false,"message":"upload error. see C:\\Users\\Andy\\AppData\\Roaming\\picgo\\picgo.log for more detail."}

### ISSUE THREAD

**Issue by AndyZhou6688** [coding-newbies-group/programming-co_creation-docs#90]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Windows11
> 编译器：VSCode
> Python版本：3.11.2
> 你的代码（描述操作）：print(Hello Python)
> 你的报错（提供报错）：上传图片失败。错误信息: {"success":false,"message":"upload error. see C:\\Users\\Andy\\AppData\\Roaming\\picgo\\picgo.log for more detail."}
>
![4](https://user-images.githubusercontent.com/85618947/224474965-e6758e1c-5ecb-4e4c-bc84-405caae6523a.png)

![3](https://user-images.githubusercontent.com/85618947/224474973-e07121b1-a975-48ee-a401-89f10af20667.png)
![2](https://user-images.githubusercontent.com/85618947/224474983-73cb947c-deac-4a75-9e5e-8c76d95e7270.png)
![1](https://user-images.githubusercontent.com/85618947/224474984-40aa51c1-342e-4fe4-8d81-f093c8162973.png)

> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```

**Comment by AndyZhou6688** [comment]
![图片](https://user-images.githubusercontent.com/85618947/224475047-84f10fdf-3f69-49df-a5d5-e4d19e85357f.png)
补充github仓库截图

**Comment by vwumumu** [comment]
教程中已经提到。
![image](https://user-images.githubusercontent.com/81784095/224475260-272b120b-d04d-48ef-9ec3-cb5bbd0258fa.png)

**Comment by AndyZhou6688** [comment]
![0](https://user-images.githubusercontent.com/85618947/224477054-1d883a07-3f97-4591-ae96-51d70a0515cb.png)
谢谢解答。如图：在看教程时注意到了这一点，但遇到的问题是：1.picgo验证失败；2.Typora插入图片也显示失败，图片地址并不是github地址

**Comment by vwumumu** [comment]
感觉是不是 / 的两边都有空格？把空格都去掉
![image](https://user-images.githubusercontent.com/81784095/224479734-2254357e-a790-4af2-ba7b-8993b9eb4ced.png)

**Comment by AndyZhou6688** [comment]
谢谢Mumu，把空格去掉就好了，我是直接在github仓库页面粘贴的仓库名称，带进来两个空格，去掉空格就好了，如图：
![1](https://user-images.githubusercontent.com/85618947/224479946-49a5f432-c999-42ac-83ac-2a0f08ccf4e9.png)

**Comment by vwumumu** [comment]
问题解决后，请关闭issues

**Comment by Zhangjuanlli** [comment]
![5e643b7b-1b85-4b85-8953-299770b768dd](https://user-images.githubusercontent.com/68979481/224594425-1996d67e-3b47-4625-8055-085ccb562050.jpg)

图中圈起的部分内容应当是与当下issue有关的，无关的内容应该删除奥
