### ISSUE TITLE
1-5 函数：代码练习没有错误，但也没有输出结果

### ISSUE THREAD

**Issue by elastigirlYY** [coding-newbies-group/programming-co_creation-docs#92]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：Mac OS
> 编译器：VSCode
> Python版本：3.9
> 你的代码（描述操作）：见图
> 你的报错（提供报错）：无报错
<img width="1440" alt="截屏2023-03-11 11 43 07" src="https://user-images.githubusercontent.com/79432716/224522206-e52eda4c-3d93-4fea-9062-1a820008e815.png">
<img width="1023" alt="截屏2023-03-12 11 14 59" src="https://user-images.githubusercontent.com/79432716/224522210-422796b0-fad6-4675-9da4-112bc569e9b2.png">

注：就算显示在终端，一点运行，又跳转到输出的页面
>
> ```
> >>> print(Hello Python)
>   File "<stdin>", line 1
>     print(Hello Python)
>           ^^^^^^^^^^^^
> SyntaxError: invalid syntax. Perhaps you forgot a comma?
> ```

**Comment by vwumumu** [comment]
先点运行，然后再点终端有结果吗？都不行把vscode卸载重装下试试
![image](https://user-images.githubusercontent.com/81784095/224530826-c7565c88-8695-4fd8-8e32-09856be80e58.png)

**Comment by vwumumu** [comment]
你github名字也没改，不知道你是谁，请关注群消息。

**Comment by Zhangjuanlli** [comment]
![image](https://user-images.githubusercontent.com/68979481/224590972-ae3304a2-bac1-4236-bece-11821c608e3b.png)

是否是因为你的代码没有保存，我犯过同样的错误，ctrl + s 保存代码，在运行就可以。我当初是粗暴地关闭了编译器，好在系统在我关闭时帮我保存了，当我再次打开编译器时，也就能运行了。不过我的是运气好，系统保存了，如果没有保存，就前功尽弃，还不知道错在哪里。
![30b80789-582f-48b3-b151-5e5197743292](https://user-images.githubusercontent.com/68979481/224592294-d923ece2-4205-4cc5-a5ab-4672fe7b3bba.jpg)

后来MUMU的指正如上图。
你的：
![984ea3bf-d8e3-431d-a234-ea83fa3ee84b](https://user-images.githubusercontent.com/68979481/224592415-c83edbdf-4e73-4fac-ab97-2b6cfb0c0e79.jpg)
