### ISSUE TITLE
5.通过Github共创  如何 更新本地的仓库 ?

### ISSUE THREAD

**Issue by skymapcn** [coding-newbies-group/programming-co_creation-docs#94]
5.通过Github共创  如何 更新本地的仓库 ?

**Comment by vwumumu** [comment]
1.sync你自己的github，让其与公共仓库同步；
2.在本地git clone下来的那个文件夹，执行git pull；
git push是向github推，git pull是从github向本地拉

**Comment by DSH5200** [comment]
MUMU更新了那个共创的视频，你可以边做边看。我对你的问题是理解是，你是想更改本地仓库，然后提交PR对吗？具体卡在哪一步呢？可以说说具体的问题，然后我们再讨论下如何处理。

对于PR，我刚开始弄的时候，真的是苦苦挣扎。现在是梳理清楚了。过了这阵子，就好了。

1. 先要把自己GITHUB仓库和小白慢爬营fork起来。
2. 把仓库下载到本地，就是git clone
3. 然后在本地文件夹修改，添加对应的文件。一般是在programming-co_creation-docs文件夹下面的docs文件
4. powershell里面运行git add .
5. powershell里面运行git commit -m "update 修改了什么”
6. 最后一步就是git push
7. 再回到仓库里，提交PR就大功告成
