### ISSUE TITLE
1-7.逻辑判断与分支：更改代码后为何机器人回答不一致

### ISSUE THREAD

**Issue by elastigirlYY** [coding-newbies-group/programming-co_creation-docs#98]
**Github Issues的标题需要以教程文章标题作为开头，否则会不予回答，请悉知**

> 系统：macOS 
> 编译器：VSCode
> Python版本：3.9
> 代码：将 else if (msg.data === "你好")修改后,保存并运行，在密信机器人输入“你是谁”时，仍然回答“我是编程学习小助手“
const { BlazeClient } = require("mixin-node-sdk");
const client = new BlazeClient(
  {
    
      "pin": "109648",
      "client_id": "a5386bd3-c744-4b28-9045-18dfe804910f",
      "session_id": "97341927-49d1-42cd-a83e-2eb1b8fb8bfc",
      "pin_token": "7aGd9rcxpd-_fW9ETYJNmln8oxNtQ7eBBHB6VEHrHHY",
      "private_key": "Nt8WQjpeXHRDAmDvufmTQ6xB_QRHz0kxJr-oW52BAjGzkmqi5ydlFbMMVYt_c26EE09EgDc3JOFf7nHaTgCCXA"
    
  },
  // 上面{ }内的信息替换成您自己Mixin机器人的私钥信息
  { parse: true, syncAck: true }
);

client.loopBlaze({
  onMessage(msg) {
    if (msg.data === "你好") {
      client.sendMessageText(msg.user_id, "你也好！");
    } else if (msg.data === "你好") {
      client.sendMessageText(msg.user_id, "我是编程学习小助手");
    } else {
      client.sendMessageText(msg.user_id, "我不知道你在说什么");
    }
  },
  onAckReceipt() {},
});

<img width="1440" alt="截屏2023-03-13 17 20 46" src="https://user-images.githubusercontent.com/79432716/224659670-da8edd37-8345-4288-bbfd-2838e461b377.png">

<img width="1278" alt="截屏2023-03-13 16 57 30" src="https://user-images.githubusercontent.com/79432716/224658821-37763901-ac6f-4b92-bd1a-edf743f2b996.png">

**Comment by DSH5200** [comment]
保存一下index.js这个文件，再重新试下。

**Comment by LazzaroneS** [comment]
你描述的这个似乎是违背了代码逻辑，我也经历过一些类似的时刻，但是大多数情况是最后会发现，是我自己哪里没搞对，代码逻辑是可靠的。所以我的个人经验是，问题更可能出在你在上面的描述之外。比如说，有可能是你上面的 index.js 和你实际执行的 index.js 并不是同一个，毕竟把核心代码文件命名为 index.js 是 node 项目的惯例。

**Comment by xiong321123** [comment]
我之前也遇到过index.js文件内咯修改后保存，机器人依然执行之前的回答。后来我就将新的内容存入到其他的js文件中，比如放在index2.js中。然后进入powershell中运行node index2.js，
<img width="307" alt="1678770471(1)" src="https://user-images.githubusercontent.com/91486483/224899642-e85332d9-3f3c-43c2-ae41-bbe14ea00842.png">
（将上图中的的node index.js换成node index2.js）

这个时候机器人就会按照新的内容来回答了。

**Comment by v5368965** [comment]
更改代码并保存的同时，**命令行窗口node也要终止一下**（ctr+c），然后重新运行“node index.js"，应该就可以了。

**Comment by elastigirlYY** [comment]
感谢各位的解答，综合各位的答案，晚上又和mumu沟通后，最后将结论总结如下：
着急先看结论：
vs code修改代码后，要使用terminal的zsh ，cd进入index所在文件夹，然后运行node index.js。

我尝试了四种方式来对比结果：
1.vs code 修改代码后，点击保存，没有运行——机器人回答修改前的答案；
2.vs code 修改代码后，点击保存，按F5运行——机器人回答修改前的答案；
3.vs code 修改代码后，点击保存，terminal运行——同时出现修改前和修改后的两个答案。
4.vs code 修改代码后，点击保存，在当前terminal窗口按 control + c，然后再打开一个terminal，运行node index.js——出现修改后的答案。
**重点** ：通过第3、4步，我才意识到，关闭zsh窗口并不能中断代码运行，需要按control + c 才能彻底中断代码，否则机器人。
其实大家回答中已经说了以上的方法，但是没有对比前我确实没看懂答案。虽然我还是不知道为什么vs code中修改代码非要terminal运行才可以生效，但先这样操作用起来吧，问题解决，感谢各位了！
